import numpy as np, time
from scipy.sparse import csr_matrix

from shadowgrouping_v2.shadowgrouping_my_dev.helper_functions import encode_setting_token

class _AllocationMixin:
    """
    Offline budget-allocation backend for ShadowGrouping energy-estimation schemes.

    Assumes the concrete class provides:
      - self.obs
      - self.num_obs
      - self.num_qubits
      - self.w
      - self.total_rounds
      - self.cliques_pool
      - self.is_overlapping
      - self.settings_dict
      - self.settings_buffer
      - self.seen_settings
      - self._is_hit_rows_used
      - self.N_hits
      - self.N_hits_pairs
      - self._append_is_hit_row(...)

    Optional concrete-class attributes:
      - self.informed_allocation
      - self.prior_counts
      - self.allocation_objective
      - self.attempt_truncation
      - self.md_gap_tol_rel
      - self.md_execution_mode
      - self.md_max_time
      - self.enable_pre_pruning
      - self.verbose
      - self.truncation_num_candidates
      - self.truncation_min_active

    Energy-estimation objectives
    ----------------------------
    The allocation objective is written as

        sum_j a_j / N_j^p,

    where N_j is the effective number of samples for Pauli string j.

    Supported allocation objectives:

      1) allocation_objective = "variance"

            a_j = |w_j|^2
            p   = 1

         This corresponds to the usual diagonal variance proxy

            sum_j |w_j|^2 / N_j.

      2) allocation_objective = "bernstein_l1"

            a_j = |w_j|
            p   = 1/2

         This corresponds to the ShadowGrouping/Bernstein-style quantity

            sum_j |w_j| / sqrt(N_j).

    Truncation convention
    ---------------------
    If self.attempt_truncation is True, candidate active sets are generated by
    ranking Pauli strings by |w_j|. The allocation objective ignores inactive
    Pauli strings by setting their optimization weights to zero.

    The full group pool is still used, so inactive Pauli strings may still be
    measured incidentally.

    Candidate truncation cuts are evaluated after integer rounding.

      - variance mode:

            total_proxy =
                sum_{measured j} |w_j|^2 / N_j
                +
                (sum_{unmeasured j} |w_j|)^2

      - bernstein_l1 mode:

            total_proxy =
                sum_{measured j} |w_j| / sqrt(N_j)
                +
                sum_{unmeasured j} |w_j|

    Independently of whether objective-level truncation is attempted, marginal
    integer rounding uses the corresponding full post-rounded proxy. The final
    statistical, truncation, coverage, and total-proxy diagnostics are stored in
    ``self.post_rounded_proxy_info``.

    Integer rounding
    ----------------
    The relaxed allocation is floored and leftover shots are assigned one at a
    time to the group with the largest finite-difference decrease in the full
    post-rounded proxy, including the truncation penalty associated with every
    positive-weight observable whose effective count is zero. Selection is with
    replacement.

    Relaxed overlapping solver accuracy
    -----------------------------------
    The relaxed overlapping allocation problem is solved approximately using
    exponentiated-gradient mirror descent on the simplex with conservative
    monotonic backtracking. The accepted step size is carried between iterations,
    enlarged mildly after successful steps, and reduced when a trial point fails
    to lower the relaxed objective.

    The convergence certificate is the relative Frank-Wolfe gap,

        gap_rel = gap_FW / max(abs(objective), abs(initial_objective), 1e-300),

    where

        gap_FW = <grad, K> - min_g grad_g.

    For convex minimization over the simplex, gap_FW upper-bounds the relaxed
    suboptimality F(K) - F(K*).

    The concrete class may provide the following solver controls:

        self.md_gap_tol_rel
        self.md_execution_mode = "default" | "until-converged" | "user-selected"
        self.md_max_time       = positive seconds in "user-selected" mode
        self.enable_pre_pruning
        self.verbose

    Recommended md_gap_tol_rel values:
        1e-3 : fast optimization
        1e-4 : default
        1e-6 : high accuracy

    In verbose mode, progress is printed approximately every five seconds.
    Other mirror-descent constants remain internal.
    """

    # ------------------------------------------------------------------
    # Objective setup
    # ------------------------------------------------------------------

    def _energy_objective_params(self):
        """
        Return the energy-estimation objective parameters.

        Returns
        -------
        abs_coeffs : np.ndarray
            |w_j|.

        objective_weights : np.ndarray
            a_j in the power-law objective sum_j a_j / N_j^p.

        objective_power : float
            p in the power-law objective.

        objective_mode : str
            Canonical objective name: "variance" or "bernstein_l1".
        """
        abs_coeffs = np.abs(np.asarray(self.w, dtype=np.float64)).reshape(-1)

        if abs_coeffs.shape != (self.num_obs,):
            raise ValueError(
                f"self.w must have shape ({self.num_obs},), got {abs_coeffs.shape}."
            )

        mode = str(
            getattr(self, "allocation_objective", "variance")
        ).strip().lower()

        if mode == "variance":
            objective_weights = abs_coeffs * abs_coeffs
            objective_power = 1.0
            objective_mode = "variance"

        elif mode == "bernstein_l1":
            objective_weights = abs_coeffs.copy()
            objective_power = 0.5
            objective_mode = "bernstein_l1"

        else:
            raise ValueError(
                "allocation_objective must be either 'variance' or "
                f"'bernstein_l1'. Got {mode!r}."
            )

        return abs_coeffs, objective_weights, objective_power, objective_mode

    @staticmethod
    def _required_obs_mask(objective_weights: np.ndarray, b: np.ndarray) -> np.ndarray:
        """
        Observables that must remain newly coverable by the allocated scheme
        because they have positive objective weight and zero prior counts.

        This is only used to keep the relaxed continuous objective well-defined.
        It does not force the final rounded integer allocation to measure every
        such observable.
        """
        return (objective_weights > 0.0) & (b <= 0.0)

    @staticmethod
    def _simplex_frank_wolfe_gap(K: np.ndarray, grad: np.ndarray) -> float:
        """
        Frank-Wolfe dual gap for minimization over the probability simplex.

        For convex differentiable F over the simplex,

            gap_FW(K) = <grad, K> - min_g grad_g

        satisfies

            F(K) - F(K*) <= gap_FW(K).
        """
        K = np.asarray(K, dtype=np.float64)
        grad = np.asarray(grad, dtype=np.float64)

        if K.size == 0:
            return 0.0

        gap = float(np.dot(grad, K) - np.min(grad))
        return max(0.0, gap)

    @staticmethod
    def _safe_prune_with_priors(tokens, members, K, objective_weights, b, tol):
        """
        Drop tiny-K overlapping groups only if doing so does not remove the last
        new-coverage route for any observable with positive objective weight and
        zero prior counts.

        Observables with positive prior counts may be left uncovered by the new
        scheme, since their denominator remains finite through b_j.
        """
        G = len(members)
        if G == 0:
            return tokens, members, K

        M = len(objective_weights)
        required = _AllocationMixin._required_obs_mask(objective_weights, b)

        cc = np.zeros(M, dtype=np.int32)
        for gg in range(G):
            req_mem = members[gg][required[members[gg]]]
            if req_mem.size > 0:
                cc[req_mem] += 1

        keep = np.ones(G, dtype=bool)

        for gg in np.argsort(K, kind="mergesort"):
            if K[gg] >= tol:
                break

            mem = members[gg]
            req_mem = mem[required[mem]]

            if req_mem.size == 0:
                keep[gg] = False
                continue

            if np.all(cc[req_mem] > 1):
                cc[req_mem] -= 1
                keep[gg] = False

        # Avoid returning an empty group pool.
        if not np.any(keep):
            keep[int(np.argmax(K))] = True

        if np.all(keep):
            return tokens, members, K

        new_tokens = [t for t, k in zip(tokens, keep) if k]
        new_members = [m for m, k in zip(members, keep) if k]
        new_K = K[keep]

        sK = float(np.sum(new_K))
        if sK <= 0.0:
            new_K = np.full(len(new_members), 1.0 / len(new_members), dtype=np.float64)
        else:
            new_K = new_K / sK

        return new_tokens, new_members, new_K

    # ------------------------------------------------------------------
    # Non-overlapping informed allocation
    # ------------------------------------------------------------------

    @staticmethod
    def _solve_nonoverlap_power_with_priors(
        members,
        objective_weights,
        objective_power,
        b,
        B,
        max_outer=80,
        max_inner=80,
    ):
        """
        Solve the exact convex non-overlapping informed allocation:

            minimize_x  sum_g sum_{j in g} a_j / (b_j + x_g)^p
            subject to  x_g >= 0,  sum_g x_g = B.

        Returns
        -------
        raw : np.ndarray
            Real-valued group allocations.
        """
        G = len(members)
        raw = np.zeros(G, dtype=np.float64)

        if B <= 0 or G == 0:
            return raw

        objective_weights = np.asarray(objective_weights, dtype=np.float64)
        b = np.asarray(b, dtype=np.float64)
        p = float(objective_power)

        if not np.any(objective_weights > 0.0):
            raw[:] = float(B) / float(G)
            return raw

        a_groups = [np.asarray(objective_weights[mem], dtype=np.float64) for mem in members]
        b_groups = [np.asarray(b[mem], dtype=np.float64) for mem in members]

        def group_x_for_lambda(ag, bg, lam):
            positive = ag > 0.0

            if ag.size == 0 or not np.any(positive):
                return 0.0

            if np.any((bg[positive] <= 0.0)):
                phi0 = np.inf
            else:
                phi0 = float(
                    p * np.sum(ag[positive] / (bg[positive] ** (p + 1.0)))
                )

            if np.isfinite(phi0) and phi0 <= lam:
                return 0.0

            lo = 0.0
            hi = 1.0

            while True:
                denom = bg + hi
                phi_hi = float(p * np.sum(ag / (denom ** (p + 1.0))))
                if phi_hi <= lam:
                    break
                hi *= 2.0

            for _ in range(max_inner):
                mid = 0.5 * (lo + hi)
                denom = bg + mid
                phi_mid = float(p * np.sum(ag / (denom ** (p + 1.0))))

                if phi_mid > lam:
                    lo = mid
                else:
                    hi = mid

            return hi

        def total_x_for_lambda(lam):
            s = 0.0
            xs = np.empty(G, dtype=np.float64)

            for gg in range(G):
                xg = group_x_for_lambda(a_groups[gg], b_groups[gg], lam)
                xs[gg] = xg
                s += xg

            return s, xs

        lam_hi = 1.0
        s_hi, _ = total_x_for_lambda(lam_hi)

        while s_hi > B:
            lam_hi *= 2.0
            s_hi, _ = total_x_for_lambda(lam_hi)

        lam_lo = lam_hi
        while True:
            lam_lo *= 0.5
            s_lo, _ = total_x_for_lambda(lam_lo)

            if s_lo >= B:
                break

            if lam_lo < 1e-300:
                break

        best_x = None

        for _ in range(max_outer):
            lam_mid = 0.5 * (lam_lo + lam_hi)
            s_mid, x_mid = total_x_for_lambda(lam_mid)

            best_x = x_mid

            if s_mid >= B:
                lam_lo = lam_mid
            else:
                lam_hi = lam_mid

        if best_x is None:
            _, best_x = total_x_for_lambda(lam_hi)

        return best_x

    # ------------------------------------------------------------------
    # Rounding helpers
    # ------------------------------------------------------------------

    def _round_raw_allocation_marginal(
        self,
        raw: np.ndarray,
        B: int,
        members,
        objective_weights: np.ndarray,
        objective_power: float,
        b: np.ndarray,
        *,
        objective_mode: str = "variance",
        truncation_cost: np.ndarray | None = None,
    ) -> np.ndarray:
        """
        Marginal-gain rounding for the leftover budget.

        For a measured observable with effective count N_j > 0, the exact
        finite-difference gain is

            a_j * [N_j^{-p} - (N_j + 1)^{-p}].

        Zero-count positive-weight observables are handled through the same
        post-rounded truncation penalty used to evaluate the final scheme:

          - bernstein_l1 mode uses the exact zero first-sample gain of

                statistical_proxy + truncation_bias;

          - variance mode uses the exact group-level finite difference of

                statistical_proxy + truncation_bias^2.
        """
        raw = np.asarray(raw, dtype=np.float64)
        objective_weights = np.asarray(objective_weights, dtype=np.float64)
        b = np.asarray(b, dtype=np.float64)
        p = float(objective_power)

        if truncation_cost is None:
            truncation_cost = np.zeros_like(objective_weights)
        else:
            truncation_cost = np.asarray(truncation_cost, dtype=np.float64)

        G = int(raw.size)
        M = int(self.num_obs)

        if G == 0:
            return np.zeros(0, dtype=np.int64)

        if B <= 0:
            return np.zeros(G, dtype=np.int64)

        raw = np.maximum(raw, 0.0)

        s_raw = float(np.sum(raw))
        if s_raw > 0.0:
            raw = raw * (float(B) / s_raw)

        reps = np.floor(raw).astype(np.int64)
        leftover = int(B) - int(np.sum(reps))

        if leftover < 0:
            raise RuntimeError(
                "Floor-rounded allocation exceeds the total budget. "
                "This should not happen unless raw allocation is inconsistent."
            )

        if leftover == 0:
            return reps

        counts = self._counts_from_allocation(members, reps).astype(np.float64)
        rounding_residual = raw - reps.astype(np.float64)

        positive_weight = objective_weights > 0.0
        objective_mode = str(objective_mode).lower()

        for _ in range(leftover):
            N_eff = b + counts

            marginal_obs = np.zeros(M, dtype=np.float64)

            measured = positive_weight & (N_eff > 0.0)
            if np.any(measured):
                marginal_obs[measured] = objective_weights[measured] * (
                    N_eff[measured] ** (-p)
                    -
                    (N_eff[measured] + 1.0) ** (-p)
                )

            if objective_mode == "bernstein_l1":
                # First sample changes |w_j| -> |w_j| / sqrt(1) = |w_j|,
                # so the first-sample gain is zero under the linear
                # statistical + truncation-bias proxy.
                group_scores = np.empty(G, dtype=np.float64)
                for gg in range(G):
                    group_scores[gg] = float(np.sum(marginal_obs[members[gg]]))

            elif objective_mode == "variance":
                # Exact group-level finite difference of
                #
                #   stat + T^2,
                #
                # where T = sum_{unmeasured j} |w_j|.
                tail_mask = (truncation_cost > 0.0) & (N_eff <= 0.0)
                T = float(np.sum(truncation_cost[tail_mask]))

                group_scores = np.empty(G, dtype=np.float64)

                for gg in range(G):
                    mem = members[gg]

                    score = float(np.sum(marginal_obs[mem]))

                    zero_mem = mem[(truncation_cost[mem] > 0.0) & (N_eff[mem] <= 0.0)]

                    if zero_mem.size > 0:
                        Cg = float(np.sum(truncation_cost[zero_mem]))
                        Qg = float(np.sum(truncation_cost[zero_mem] ** 2))

                        # Gain from removing those zero-count terms from the
                        # truncation tail while adding their one-sample variance.
                        score += 2.0 * T * Cg - Cg * Cg - Qg

                    group_scores[gg] = score

            else:
                raise ValueError(f"Unknown objective_mode={objective_mode!r}.")

            best_score = float(np.max(group_scores))
            candidates = np.flatnonzero(group_scores == best_score)

            if candidates.size == 1:
                g_best = int(candidates[0])
            else:
                local = rounding_residual[candidates]
                g_best = int(candidates[int(np.argmax(local))])

            reps[g_best] += 1
            rounding_residual[g_best] -= 1.0

            counts[members[g_best]] += 1.0

        return reps

    def _round_continuous_allocation(
        self,
        raw: np.ndarray,
        B: int,
        members,
        objective_weights: np.ndarray,
        objective_power: float,
        b: np.ndarray,
        *,
        objective_mode: str = "variance",
        truncation_cost: np.ndarray | None = None,
    ) -> np.ndarray:
        """
        Floor the relaxed allocation and assign every leftover shot by the
        exact marginal decrease in the post-rounded energy proxy.
        """
        return self._round_raw_allocation_marginal(
            raw=raw,
            B=B,
            members=members,
            objective_weights=objective_weights,
            objective_power=objective_power,
            b=b,
            objective_mode=objective_mode,
            truncation_cost=truncation_cost,
        )

    @staticmethod
    def _uniform_reps(G: int, B: int) -> np.ndarray:
        """
        Uniform integer allocation over G groups.
        """
        G = int(G)
        B = int(B)

        if G <= 0:
            return np.zeros(0, dtype=np.int64)

        if B <= 0:
            return np.zeros(G, dtype=np.int64)

        reps = np.full(G, B // G, dtype=np.int64)
        leftover = B - int(np.sum(reps))

        for i in range(leftover):
            reps[i % G] += 1

        return reps

    # ------------------------------------------------------------------
    # State updates and diagnostics
    # ------------------------------------------------------------------

    def _clear_new_scheme_state(self):
        """
        Clear only the state associated with the newly allocated scheme.
        """
        self.settings_dict = {}
        self.settings_buffer = {}
        self.seen_settings = set()
        self._is_hit_rows_used = 0
        self.N_hits[:] = 0

        if hasattr(self, "N_hits_pairs"):
            self.N_hits_pairs[:] = 0

    def _commit_allocation(self, tokens, members, reps):
        """
        Commit a new integer allocation to settings_dict/settings_buffer and
        update N_hits and N_hits_pairs.
        """
        M = int(self.num_obs)

        for gg in range(len(members)):
            r = int(reps[gg])
            if r <= 0:
                continue

            tok = tokens[gg]
            clique = members[gg]

            self.settings_dict[tok] = self.settings_dict.get(tok, 0) + r
            self.settings_buffer[tok] = self.settings_buffer.get(tok, 0) + r
            self.seen_settings.add(tok)

            row = np.zeros(M, dtype=bool)
            row[clique] = True
            self._append_is_hit_row(row)

            self.N_hits[clique] += r

            if hasattr(self, "N_hits_pairs"):
                self.N_hits_pairs[np.ix_(clique, clique)] += r

    def _counts_from_allocation(self, members, reps):
        """
        Compute per-observable newly allocated counts for a candidate allocation
        without committing it.
        """
        counts = np.zeros(int(self.num_obs), dtype=np.int64)

        for gg in range(len(members)):
            r = int(reps[gg])
            if r <= 0:
                continue
            counts[members[gg]] += r

        return counts

    @staticmethod
    def _energy_proxy_from_counts(
        abs_coeffs,
        objective_weights,
        objective_power,
        objective_mode,
        b,
        new_counts,
    ):
        """
        Evaluate the post-rounded energy-estimation proxy.

        variance mode:
            total = sum_measured |w_j|^2 / N_j
                    +
                    (sum_unmeasured |w_j|)^2

        bernstein_l1 mode:
            total = sum_measured |w_j| / sqrt(N_j)
                    +
                    sum_unmeasured |w_j|
        """
        abs_coeffs = np.asarray(abs_coeffs, dtype=np.float64)
        objective_weights = np.asarray(objective_weights, dtype=np.float64)
        b = np.asarray(b, dtype=np.float64)
        new_counts = np.asarray(new_counts, dtype=np.float64)
        p = float(objective_power)

        N_eff = b + new_counts
        measured = N_eff > 0.0

        stat_proxy = 0.0
        if np.any(measured):
            stat_proxy = float(
                np.sum(objective_weights[measured] / (N_eff[measured] ** p))
            )

        trunc_bias = float(np.sum(abs_coeffs[~measured]))

        objective_mode = str(objective_mode).lower()

        if objective_mode == "variance":
            total_proxy = stat_proxy + trunc_bias * trunc_bias

        elif objective_mode == "bernstein_l1":
            total_proxy = stat_proxy + trunc_bias

        else:
            raise ValueError(f"Unknown objective_mode={objective_mode!r}.")

        return total_proxy, stat_proxy, trunc_bias, measured

    def _store_post_rounded_proxy_info(
        self,
        *,
        abs_coeffs,
        objective_weights,
        objective_power,
        objective_mode,
        b,
        members,
        reps,
        reason="allocation_completed",
    ):
        """
        Evaluate and store diagnostics for the final integer allocation.

        The measured set is defined from the effective counts

            N_eff = prior_counts + newly_allocated_counts,

        so the diagnostics capture rounding-induced truncation whether or not
        objective-level truncation was requested.
        """
        reps = np.asarray(reps, dtype=np.int64).reshape(-1)
        new_counts = self._counts_from_allocation(members, reps)

        total_proxy, stat_proxy, trunc_bias, measured = (
            self._energy_proxy_from_counts(
                abs_coeffs=abs_coeffs,
                objective_weights=objective_weights,
                objective_power=objective_power,
                objective_mode=objective_mode,
                b=b,
                new_counts=new_counts,
            )
        )

        abs_coeffs = np.asarray(abs_coeffs, dtype=np.float64).reshape(-1)
        positive = abs_coeffs > 0.0
        measured_positive = positive & measured
        unmeasured_positive = positive & ~measured

        if str(objective_mode).lower() == "variance":
            truncation_penalty = float(trunc_bias * trunc_bias)
        else:
            truncation_penalty = float(trunc_bias)

        self.post_rounded_proxy_info = {
            "available": True,
            "reason": str(reason),
            "allocation_objective": str(objective_mode),
            "objective_power": float(objective_power),
            "total_rounds_requested": int(self.total_rounds),
            "num_rounds_allocated": int(np.sum(reps)),
            "num_groups_considered": int(len(members)),
            "num_groups_with_nonzero_reps": int(np.count_nonzero(reps > 0)),
            "num_measured_observables": int(np.count_nonzero(measured)),
            "num_unmeasured_observables": int(np.count_nonzero(~measured)),
            "num_positive_weight_observables": int(np.count_nonzero(positive)),
            "num_measured_positive_weight_observables": int(
                np.count_nonzero(measured_positive)
            ),
            "num_truncated_positive_weight_observables": int(
                np.count_nonzero(unmeasured_positive)
            ),
            "actual_truncation_after_rounding": bool(
                np.any(unmeasured_positive)
            ),
            "stat_proxy": float(stat_proxy),
            "trunc_bias": float(trunc_bias),
            "truncation_bias_bound": float(trunc_bias),
            "squared_truncation_bias_bound": float(trunc_bias * trunc_bias),
            "truncation_penalty": float(truncation_penalty),
            "total_proxy": float(total_proxy),
        }

        return self.post_rounded_proxy_info

    # ------------------------------------------------------------------
    # Truncation candidate generation
    # ------------------------------------------------------------------

    def _truncation_candidate_sizes(self, num_positive: int) -> np.ndarray:
        """
        Candidate numbers of active observables to keep.

        Uses a logarithmic-scale scan. The largest candidate is num_positive,
        corresponding to no objective-level truncation among positive-weight
        Pauli strings.

        Optional concrete-class attributes:
          - self.truncation_num_candidates
          - self.truncation_min_active
        """
        num_positive = int(num_positive)

        if num_positive <= 0:
            return np.zeros(0, dtype=np.int64)

        default_num = min(
            32,
            max(2, int(np.ceil(np.log2(max(num_positive, 2)))) + 1),
        )

        num_candidates = int(getattr(self, "truncation_num_candidates", default_num))
        num_candidates = max(1, num_candidates)

        min_active = int(getattr(self, "truncation_min_active", 1))
        min_active = max(1, min(min_active, num_positive))

        if min_active == num_positive:
            return np.array([num_positive], dtype=np.int64)

        sizes = np.unique(
            np.round(
                np.geomspace(min_active, num_positive, num=num_candidates)
            ).astype(np.int64)
        )

        sizes = sizes[(sizes >= min_active) & (sizes <= num_positive)]

        sizes = np.unique(
            np.concatenate((sizes, np.array([num_positive], dtype=np.int64)))
        )

        return sizes.astype(np.int64, copy=False)

    # ------------------------------------------------------------------
    # Overlapping informed allocation
    # ------------------------------------------------------------------

    def _solve_overlapping_power_with_priors(
        self,
        tokens_in,
        members_in,
        objective_weights,
        objective_power,
        b,
        B,
        *,
        objective_mode: str,
        truncation_cost: np.ndarray | None = None,
        rounding_objective_weights: np.ndarray | None = None,
    ):
        """
        Solve the overlapping informed allocation for a fixed power-law objective:

            minimize_K sum_j a_j / (b_j + B chi_j(K))^p
            subject to K_g >= 0, sum_g K_g = 1.

        The solver uses exponentiated-gradient mirror descent on the simplex
        with conservative monotonic backtracking. Convergence is certified with
        the relative Frank-Wolfe gap.

        Execution modes
        ---------------
        ``self.md_execution_mode`` must be one of:

          - ``"default"``:
                At most 1000 mirror-descent updates per run. The solver uses an
                initial run and, if needed, one step-size restart from the best
                objective point found by the initial run.

          - ``"until-converged"``:
                One uninterrupted mirror-descent trajectory with no iteration or
                wall-clock limit. The solver stops only after reaching the gap
                target or encountering a genuine numerical failure.

          - ``"user-selected"``:
                One uninterrupted mirror-descent trajectory with no iteration
                limit and a positive wall-clock limit ``self.md_max_time`` in
                seconds. If the time limit is reached before convergence, the
                returned point is the iterate with the smallest relative
                Frank-Wolfe gap encountered during the run.

        Optional concrete-class attributes
        ----------------------------------
        md_gap_tol_rel : float
            Relative Frank-Wolfe-gap target. Default: 1e-4.
        md_execution_mode : str
            ``"default"``, ``"until-converged"``, or ``"user-selected"``.
            Default: ``"default"``.
        md_max_time : float or None
            Positive time limit in seconds. Required only in
            ``"user-selected"`` mode and rejected in the other modes.
        enable_pre_pruning : bool
            Whether to prune tiny warm-start weights before optimization.
            Default: True.
        verbose : bool
            If True, print stage transitions and optimization progress at most
            once every five seconds, as well as run and final summaries.

        Notes
        -----
        There is deliberately no post-optimization pruning. The group pool is
        fixed after optional pre-pruning, so the reported Frank-Wolfe certificate
        applies to the same continuous allocation that is subsequently rounded.
        Settings receiving zero integer repetitions are omitted naturally by
        ``_commit_allocation``.
        """
        # ------------------------------------------------------------------
        # Hard-coded numerical policy.
        # ------------------------------------------------------------------
        md_default_max_iters_per_run = 1000
        md_default_num_runs = 2  # initial run + one step-size restart

        # Conservative backtracking policy. ``md_eta0`` fixes the scale of the
        # first exponentiated-gradient step through eta_0 = md_eta0 / ||g_c||_inf,
        # where g_c is the gradient centered by its K-weighted mean. After an
        # accepted step, the next trial is mildly enlarged. Rejected trials are
        # reduced geometrically until the objective strictly decreases.
        md_eta0 = 0.5
        md_backtrack_factor = 0.5
        md_growth_factor = 1.25
        md_max_backtracking_trials = 50
        md_min_eta_relative = 1e-14
        md_max_eta_relative = 1e12

        md_denominator_epsilon = 1e-12
        md_min_iters = 25
        md_verbose_interval = 5.0

        md_gap_tol_rel = float(getattr(self, "md_gap_tol_rel", 1e-4))
        if not np.isfinite(md_gap_tol_rel) or md_gap_tol_rel <= 0.0:
            raise ValueError("md_gap_tol_rel must be positive and finite.")

        execution_mode = str(
            getattr(self, "md_execution_mode", "default")
        ).strip().lower()

        valid_execution_modes = {
            "default",
            "until-converged",
            "user-selected",
        }
        if execution_mode not in valid_execution_modes:
            raise ValueError(
                "md_execution_mode must be one of 'default', "
                "'until-converged', or 'user-selected'. "
                f"Got {execution_mode!r}."
            )

        md_max_time_attr = getattr(self, "md_max_time", None)
        if execution_mode == "user-selected":
            if md_max_time_attr is None:
                raise ValueError(
                    "md_max_time must be provided when "
                    "md_execution_mode='user-selected'."
                )
            md_max_time = float(md_max_time_attr)
            if not np.isfinite(md_max_time) or md_max_time <= 0.0:
                raise ValueError(
                    "md_max_time must be positive and finite when "
                    "md_execution_mode='user-selected'."
                )
        else:
            if md_max_time_attr is not None:
                raise ValueError(
                    "md_max_time is only active when "
                    "md_execution_mode='user-selected'. Set it to None for "
                    f"md_execution_mode={execution_mode!r}."
                )
            md_max_time = None

        enable_pre_pruning = bool(getattr(self, "enable_pre_pruning", True))
        verbose = bool(getattr(self, "verbose", False))

        B = int(B)
        M = int(self.num_obs)

        tokens = list(tokens_in)
        members = [np.asarray(g, dtype=np.int32) for g in members_in]

        G = len(members)
        if B <= 0 or G == 0:
            return [], [], np.zeros(0, dtype=np.int64), {
                "relaxed_objective": None,
                "num_groups": 0,
                "flat_objective": False,
                "convergence": None,
            }

        objective_weights = np.asarray(
            objective_weights, dtype=np.float64
        ).reshape(-1)
        b = np.asarray(b, dtype=np.float64).reshape(-1)
        p = float(objective_power)

        if rounding_objective_weights is None:
            rounding_objective_weights = objective_weights
        else:
            rounding_objective_weights = np.asarray(
                rounding_objective_weights, dtype=np.float64
            ).reshape(-1)

        if truncation_cost is None:
            truncation_cost = np.zeros(M, dtype=np.float64)
        else:
            truncation_cost = np.asarray(
                truncation_cost, dtype=np.float64
            ).reshape(-1)

        if objective_weights.shape != (M,):
            raise ValueError(f"objective_weights must have shape ({M},).")
        if rounding_objective_weights.shape != (M,):
            raise ValueError(
                f"rounding_objective_weights must have shape ({M},)."
            )
        if truncation_cost.shape != (M,):
            raise ValueError(f"truncation_cost must have shape ({M},).")
        if b.shape != (M,):
            raise ValueError(f"b must have shape ({M},), got {b.shape}.")
        if np.any(objective_weights < -1e-14):
            raise ValueError("Objective weights must be nonnegative.")
        if np.any(rounding_objective_weights < -1e-14):
            raise ValueError("Rounding objective weights must be nonnegative.")
        if np.any(truncation_cost < -1e-14):
            raise ValueError("Truncation costs must be nonnegative.")
        if np.any(b < 0.0):
            raise ValueError("Prior counts must be nonnegative.")
        if p <= 0.0:
            raise ValueError("objective_power must be positive.")

        objective_weights = np.maximum(objective_weights, 0.0)
        rounding_objective_weights = np.maximum(
            rounding_objective_weights, 0.0
        )
        truncation_cost = np.maximum(truncation_cost, 0.0)

        solver_start_time = time.perf_counter()
        deadline = (
            solver_start_time + md_max_time
            if execution_mode == "user-selected"
            else None
        )

        def elapsed_time() -> float:
            return float(time.perf_counter() - solver_start_time)

        def vprint(message: str) -> None:
            if verbose:
                print(message, flush=True)

        if not np.any(objective_weights > 0.0):
            reps = self._uniform_reps(G, B)
            elapsed = elapsed_time()
            convergence = {
                "converged": True,
                "convergence_reason": "flat_objective",
                "returned_solution_selection": "uniform-flat-objective",
                "md_execution_mode": execution_mode,
                "md_max_time": md_max_time,
                "max_iters_per_run": (
                    md_default_max_iters_per_run
                    if execution_mode == "default"
                    else None
                ),
                "elapsed_time": elapsed,
                "iterations": 0,
                "total_iterations": 0,
                "objective": None,
                "frank_wolfe_gap": 0.0,
                "relative_frank_wolfe_gap": 0.0,
                "md_gap_tol_rel": float(md_gap_tol_rel),
                "best_objective_encountered": None,
                "relative_gap_at_best_objective": 0.0,
                "best_gap_encountered": 0.0,
                "best_relative_gap_encountered": 0.0,
                "objective_at_best_gap": None,
                "pre_pruning_enabled": enable_pre_pruning,
                "num_groups_initial": G,
                "num_groups_after_pre_pruning": G,
                "num_groups_after_post_pruning": G,
                "post_pruning_applied": False,
                "post_pruning_changed_pool": False,
                "num_step_size_restarts": 0,
                "num_random_restarts": 0,
                "denominator_regularization": float(
                    md_denominator_epsilon
                ),
                "incidence_matrix_nnz": 0,
                "verbose_progress_interval": float(md_verbose_interval),
                "runs": [],
            }
            vprint(
                "[allocation][done] converged=True reason=flat_objective "
                f"elapsed={elapsed:.2f}s total_iter=0"
            )
            return tokens, members, reps, {
                "relaxed_objective": None,
                "num_groups": G,
                "flat_objective": True,
                "convergence": convergence,
            }

        prune_tol = max(1e-8, 0.25 / float(max(B, 1)))
        num_groups_initial = G

        vprint(
            "[allocation][start] "
            f"groups={G} observables={M} budget={B} "
            f"mode={execution_mode} target_rel_FW_gap={md_gap_tol_rel:.3e} "
            f"pre_pruning={enable_pre_pruning}"
            + (
                f" max_time={md_max_time:.3f}s"
                if execution_mode == "user-selected"
                else ""
            )
        )

        # Warm start.
        Wg = np.zeros(G, dtype=np.float64)
        for gg in range(G):
            Wg[gg] = float(np.sum(objective_weights[members[gg]]))

        sg = np.maximum(Wg, 0.0) ** (1.0 / (p + 1.0))
        if float(np.sum(sg)) <= 0.0:
            K0 = np.full(G, 1.0 / G, dtype=np.float64)
        else:
            K0 = (sg / float(np.sum(sg))).astype(np.float64)

        if enable_pre_pruning:
            groups_before = len(members)
            tokens, members, K0 = self._safe_prune_with_priors(
                tokens,
                members,
                K0,
                objective_weights,
                b,
                prune_tol,
            )
            groups_after = len(members)
            vprint(
                "[allocation][pre-pruning] "
                f"enabled=True groups_before={groups_before} "
                f"groups_after={groups_after} prune_tol={prune_tol:.3e}"
            )
        else:
            vprint(
                "[allocation][pre-pruning] "
                f"enabled=False groups_before={len(members)} "
                f"groups_after={len(members)}"
            )

        G = len(members)
        num_groups_after_pre_pruning = G
        if G == 0:
            return [], [], np.zeros(0, dtype=np.int64), {
                "relaxed_objective": None,
                "num_groups": 0,
                "flat_objective": False,
                "convergence": None,
            }

        # Build the observable-setting incidence matrix once.
        group_sizes = np.fromiter(
            (int(mem.size) for mem in members),
            dtype=np.int64,
            count=G,
        )
        incidence_nnz = int(np.sum(group_sizes))

        if incidence_nnz > 0:
            incidence_rows = np.concatenate(members).astype(
                np.int32, copy=False
            )
            incidence_cols = np.repeat(
                np.arange(G, dtype=np.int32), group_sizes
            )
            incidence_data = np.ones(incidence_nnz, dtype=np.float64)
        else:
            incidence_rows = np.zeros(0, dtype=np.int32)
            incidence_cols = np.zeros(0, dtype=np.int32)
            incidence_data = np.zeros(0, dtype=np.float64)

        incidence_matrix = csr_matrix(
            (incidence_data, (incidence_rows, incidence_cols)),
            shape=(M, G),
            dtype=np.float64,
        )
        incidence_matrix.sum_duplicates()
        incidence_matrix.sort_indices()
        incidence_matrix_T = incidence_matrix.transpose().tocsr()

        def eval_objective_state(K):
            """
            Evaluate the relaxed objective and retain its regularized denominator.

            The denominator is returned so that, after a trial point is accepted,
            its gradient can be computed without repeating the sparse product C K.
            """
            K = np.asarray(K, dtype=np.float64)
            chi = np.asarray(incidence_matrix @ K).reshape(-1)
            denom_regularized = b + B * chi + md_denominator_epsilon
            obj = float(
                np.sum(objective_weights / (denom_regularized ** p))
            )
            return obj, denom_regularized

        def gradient_from_denominator(denom_regularized):
            inv = (
                B
                * p
                * objective_weights
                / (denom_regularized ** (p + 1.0))
            )
            return -np.asarray(incidence_matrix_T @ inv).reshape(-1)

        def eval_obj_and_grad(K):
            obj, denom_regularized = eval_objective_state(K)
            grad = gradient_from_denominator(denom_regularized)
            return obj, grad

        def exponentiated_trial(K, grad, eta):
            """
            Stable exponentiated-gradient trial point on the probability simplex.

            Subtracting the K-weighted mean of the gradient does not alter the
            normalized exponentiated update, but it reduces the dynamic range of
            the logits. The log-domain implementation avoids overflow for large
            trial step sizes.
            """
            K = np.asarray(K, dtype=np.float64)
            grad = np.asarray(grad, dtype=np.float64)

            grad_center = float(np.dot(K, grad))
            centered_grad = grad - grad_center

            logits = np.log(np.maximum(K, 1e-300)) - eta * centered_grad
            logits -= float(np.max(logits))

            K_trial = np.exp(logits)
            K_trial = np.maximum(K_trial, 1e-300)
            K_sum = float(np.sum(K_trial))

            if not np.isfinite(K_sum) or K_sum <= 0.0:
                return None

            K_trial /= K_sum
            return K_trial

        progress_state = {"last_progress_print_time": None}
        total_iterations = 0
        all_run_records = []
        total_step_size_restarts = 0

        def relative_gap(obj: float, gap: float, scale_reference: float) -> float:
            scale = max(abs(float(obj)), abs(float(scale_reference)), 1e-300)
            return float(gap / scale)

        def print_progress(
            *,
            run_label,
            iteration,
            total_iteration,
            obj,
            gap,
            rel_gap,
            run_best_rel_gap,
            stage_best_rel_gap,
            accepted_eta,
            last_backtracks,
            total_rejected_trials,
            force=False,
        ):
            if not verbose:
                return

            now = time.perf_counter()
            last = progress_state["last_progress_print_time"]
            if not force and last is not None and now - last < md_verbose_interval:
                return

            eta_text = "none" if accepted_eta is None else f"{accepted_eta:.3e}"

            print(
                f"[allocation][optimization][{run_label}] "
                f"iter={iteration} total_iter={total_iteration} "
                f"elapsed={elapsed_time():.2f}s objective={obj:.8e} "
                f"FW_gap={gap:.3e} rel_FW_gap={rel_gap:.3e} "
                f"run_best_rel_FW_gap={run_best_rel_gap:.3e} "
                f"stage_best_rel_FW_gap={stage_best_rel_gap:.3e} "
                f"target={md_gap_tol_rel:.3e} "
                f"current_target_ratio={rel_gap / md_gap_tol_rel:.3g} "
                f"run_best_target_ratio="
                f"{run_best_rel_gap / md_gap_tol_rel:.3g} "
                f"stage_best_target_ratio="
                f"{stage_best_rel_gap / md_gap_tol_rel:.3g} "
                f"eta={eta_text} last_backtracks={last_backtracks} "
                f"rejected_trials={total_rejected_trials}",
                flush=True,
            )
            progress_state["last_progress_print_time"] = now

        def mirror_descent(
            K_init,
            *,
            run_label,
            scale_reference,
            stage_best_rel_gap_before_run,
            total_iterations_before,
            max_iters,
            deadline,
            stop_selection,
        ):
            """
            Run one exponentiated-gradient trajectory with monotonic backtracking.

            ``iterations`` counts accepted mirror-descent steps. Rejected trial
            points are recorded separately and do not consume the default-mode
            iteration allowance.

            stop_selection controls which incumbent is returned if the gap target
            is not reached:
              - "best-objective" for the bounded default mode;
              - "best-relative-fw-gap" for time/numerical termination.
            """
            K = np.asarray(K_init, dtype=np.float64).copy()
            K = np.maximum(K, 1e-300)
            K /= float(np.sum(K))

            run_start_time = time.perf_counter()
            iterations = 0

            obj, denom_regularized = eval_objective_state(K)
            if not np.isfinite(obj):
                return K, K, K, {
                    "converged": False,
                    "termination_reason": "nonfinite_objective",
                    "returned_solution_selection": "initial-point",
                    "iterations": 0,
                    "elapsed_time": float(
                        time.perf_counter() - run_start_time
                    ),
                    "initial_objective": float(obj),
                    "objective": float(obj),
                    "frank_wolfe_gap": float("inf"),
                    "relative_frank_wolfe_gap": float("inf"),
                    "best_objective_encountered": float(obj),
                    "gap_at_best_objective": float("inf"),
                    "relative_gap_at_best_objective": float("inf"),
                    "best_gap_encountered": float("inf"),
                    "best_relative_gap_encountered": float("inf"),
                    "objective_at_best_gap": float(obj),
                    "step_size_strategy": "monotonic-backtracking",
                    "accepted_steps": 0,
                    "objective_trial_evaluations": 0,
                    "rejected_backtracking_trials": 0,
                }

            grad = gradient_from_denominator(denom_regularized)
            if not np.all(np.isfinite(grad)):
                return K, K, K, {
                    "converged": False,
                    "termination_reason": "nonfinite_gradient",
                    "returned_solution_selection": "initial-point",
                    "iterations": 0,
                    "elapsed_time": float(
                        time.perf_counter() - run_start_time
                    ),
                    "initial_objective": float(obj),
                    "objective": float(obj),
                    "frank_wolfe_gap": float("inf"),
                    "relative_frank_wolfe_gap": float("inf"),
                    "best_objective_encountered": float(obj),
                    "gap_at_best_objective": float("inf"),
                    "relative_gap_at_best_objective": float("inf"),
                    "best_gap_encountered": float("inf"),
                    "best_relative_gap_encountered": float("inf"),
                    "objective_at_best_gap": float(obj),
                    "step_size_strategy": "monotonic-backtracking",
                    "accepted_steps": 0,
                    "objective_trial_evaluations": 0,
                    "rejected_backtracking_trials": 0,
                }

            gap = self._simplex_frank_wolfe_gap(K, grad)
            rel_gap = relative_gap(obj, gap, scale_reference)

            initial_objective = float(obj)
            initial_gap = float(gap)
            initial_rel_gap = float(rel_gap)

            best_objective = float(obj)
            best_objective_K = K.copy()
            gap_at_best_objective = float(gap)
            rel_gap_at_best_objective = float(rel_gap)
            best_objective_iteration = 0

            best_gap_encountered = float(gap)
            best_relative_gap_encountered = float(rel_gap)
            best_gap_K = K.copy()
            objective_at_best_gap = float(obj)
            best_gap_iteration = 0

            # The centered gradient is the relevant scale because adding a
            # constant to every gradient component leaves the normalized
            # exponentiated-gradient update unchanged.
            centered_grad = grad - float(np.dot(K, grad))
            grad_scale = max(float(np.max(np.abs(centered_grad))), 1e-12)
            initial_eta = float(md_eta0 / grad_scale)
            eta_floor = max(
                np.finfo(np.float64).tiny,
                initial_eta * md_min_eta_relative,
            )
            eta_cap = max(initial_eta, initial_eta * md_max_eta_relative)
            next_eta_trial = initial_eta

            accepted_eta = None
            min_accepted_eta = float("inf")
            max_accepted_eta = 0.0
            final_accepted_eta = None
            line_search_trial_attempts = 0
            objective_trial_evaluations = 0
            rejected_backtracking_trials = 0
            max_trials_in_one_step = 0
            last_backtracks = 0

            print_progress(
                run_label=run_label,
                iteration=0,
                total_iteration=total_iterations_before,
                obj=obj,
                gap=gap,
                rel_gap=rel_gap,
                run_best_rel_gap=best_relative_gap_encountered,
                stage_best_rel_gap=min(
                    stage_best_rel_gap_before_run,
                    best_relative_gap_encountered,
                ),
                accepted_eta=None,
                last_backtracks=0,
                total_rejected_trials=0,
                force=True,
            )

            termination_reason = None

            while True:
                if iterations >= md_min_iters and rel_gap <= md_gap_tol_rel:
                    termination_reason = "frank_wolfe_gap"
                    break

                if max_iters is not None and iterations >= max_iters:
                    termination_reason = "max_iters"
                    break

                if deadline is not None and time.perf_counter() >= deadline:
                    termination_reason = "time_limit"
                    break

                eta_trial = min(next_eta_trial, eta_cap)
                trial_accepted = False
                trial_failure_reason = None
                trials_this_step = 0
                last_backtracks = 0

                while trials_this_step < md_max_backtracking_trials:
                    if deadline is not None and time.perf_counter() >= deadline:
                        trial_failure_reason = "time_limit"
                        break

                    if eta_trial < eta_floor or not np.isfinite(eta_trial):
                        trial_failure_reason = "line_search_failed"
                        break

                    K_trial = exponentiated_trial(K, grad, eta_trial)
                    trials_this_step += 1
                    line_search_trial_attempts += 1

                    if K_trial is None or not np.all(np.isfinite(K_trial)):
                        rejected_backtracking_trials += 1
                        last_backtracks += 1
                        eta_trial *= md_backtrack_factor
                        continue

                    trial_obj, trial_denom = eval_objective_state(K_trial)
                    objective_trial_evaluations += 1

                    # Stage 1 uses the deliberately conservative acceptance
                    # rule F(K_trial) < F(K). For the smooth convex objective,
                    # a sufficiently small positive step is a descent step unless
                    # the current point is stationary up to floating-point error.
                    if np.isfinite(trial_obj) and trial_obj < obj:
                        trial_accepted = True
                        break

                    rejected_backtracking_trials += 1
                    last_backtracks += 1
                    eta_trial *= md_backtrack_factor

                max_trials_in_one_step = max(
                    max_trials_in_one_step, trials_this_step
                )

                if not trial_accepted:
                    termination_reason = (
                        trial_failure_reason
                        if trial_failure_reason is not None
                        else "line_search_failed"
                    )
                    break

                K = K_trial
                obj = float(trial_obj)
                grad = gradient_from_denominator(trial_denom)
                if not np.all(np.isfinite(grad)):
                    termination_reason = "nonfinite_gradient"
                    break

                iterations += 1
                accepted_eta = float(eta_trial)
                final_accepted_eta = accepted_eta
                min_accepted_eta = min(min_accepted_eta, accepted_eta)
                max_accepted_eta = max(max_accepted_eta, accepted_eta)

                # Carry the accepted step forward and test a mildly larger one
                # at the next accepted iteration.
                next_eta_trial = min(
                    accepted_eta * md_growth_factor,
                    eta_cap,
                )

                gap = self._simplex_frank_wolfe_gap(K, grad)
                rel_gap = relative_gap(obj, gap, scale_reference)

                if obj < best_objective:
                    best_objective = float(obj)
                    best_objective_K = K.copy()
                    gap_at_best_objective = float(gap)
                    rel_gap_at_best_objective = float(rel_gap)
                    best_objective_iteration = int(iterations)

                if rel_gap < best_relative_gap_encountered:
                    best_gap_encountered = float(gap)
                    best_relative_gap_encountered = float(rel_gap)
                    best_gap_K = K.copy()
                    objective_at_best_gap = float(obj)
                    best_gap_iteration = int(iterations)

                print_progress(
                    run_label=run_label,
                    iteration=iterations,
                    total_iteration=total_iterations_before + iterations,
                    obj=obj,
                    gap=gap,
                    rel_gap=rel_gap,
                    run_best_rel_gap=best_relative_gap_encountered,
                    stage_best_rel_gap=min(
                        stage_best_rel_gap_before_run,
                        best_relative_gap_encountered,
                    ),
                    accepted_eta=accepted_eta,
                    last_backtracks=last_backtracks,
                    total_rejected_trials=rejected_backtracking_trials,
                    force=False,
                )

            converged = bool(best_relative_gap_encountered <= md_gap_tol_rel)
            if converged:
                termination_reason = "frank_wolfe_gap"
                selected_K = best_gap_K.copy()
                selected_label = "best-relative-fw-gap"
            elif stop_selection == "best-relative-fw-gap":
                selected_K = best_gap_K.copy()
                selected_label = "best-relative-fw-gap"
            else:
                selected_K = best_objective_K.copy()
                selected_label = "best-objective"

            final_obj, final_grad = eval_obj_and_grad(selected_K)
            if np.isfinite(final_obj) and np.all(np.isfinite(final_grad)):
                final_gap = self._simplex_frank_wolfe_gap(
                    selected_K, final_grad
                )
                final_rel_gap = relative_gap(
                    final_obj, final_gap, scale_reference
                )
            else:
                final_gap = float("inf")
                final_rel_gap = float("inf")

            run_elapsed = float(time.perf_counter() - run_start_time)
            accepted_steps = int(iterations)
            mean_trials = (
                float(objective_trial_evaluations) / accepted_steps
                if accepted_steps > 0
                else 0.0
            )

            info = {
                "converged": bool(final_rel_gap <= md_gap_tol_rel),
                "termination_reason": termination_reason,
                "returned_solution_selection": selected_label,
                "iterations": accepted_steps,
                "elapsed_time": run_elapsed,
                "initial_objective": initial_objective,
                "initial_frank_wolfe_gap": initial_gap,
                "initial_relative_frank_wolfe_gap": initial_rel_gap,
                "objective": float(final_obj),
                "frank_wolfe_gap": float(final_gap),
                "relative_frank_wolfe_gap": float(final_rel_gap),
                "best_objective_encountered": float(best_objective),
                "best_objective_iteration": int(best_objective_iteration),
                "gap_at_best_objective": float(gap_at_best_objective),
                "relative_gap_at_best_objective": float(
                    rel_gap_at_best_objective
                ),
                "best_gap_encountered": float(best_gap_encountered),
                "best_relative_gap_encountered": float(
                    best_relative_gap_encountered
                ),
                "objective_at_best_gap": float(objective_at_best_gap),
                "best_gap_iteration": int(best_gap_iteration),
                "step_size_strategy": "monotonic-backtracking",
                "initial_step_size": float(initial_eta),
                "final_accepted_step_size": (
                    None
                    if final_accepted_eta is None
                    else float(final_accepted_eta)
                ),
                "min_accepted_step_size": (
                    None
                    if not np.isfinite(min_accepted_eta)
                    else float(min_accepted_eta)
                ),
                "max_accepted_step_size": float(max_accepted_eta),
                "accepted_steps": accepted_steps,
                "line_search_trial_attempts": int(
                    line_search_trial_attempts
                ),
                "objective_trial_evaluations": int(
                    objective_trial_evaluations
                ),
                "rejected_backtracking_trials": int(
                    rejected_backtracking_trials
                ),
                "mean_trials_per_accepted_step": float(mean_trials),
                "max_trials_in_one_step": int(max_trials_in_one_step),
                "backtrack_factor": float(md_backtrack_factor),
                "growth_factor": float(md_growth_factor),
                "max_backtracking_trials": int(
                    md_max_backtracking_trials
                ),
            }
            return selected_K, best_objective_K, best_gap_K, info

        # Evaluate the fixed scale reference once at the deterministic warm start.
        stage_initial_obj, stage_initial_grad = eval_obj_and_grad(K0)
        if not np.isfinite(stage_initial_obj):
            raise FloatingPointError(
                "The initial overlapping-allocation objective is non-finite."
            )
        if not np.all(np.isfinite(stage_initial_grad)):
            raise FloatingPointError(
                "The initial overlapping-allocation gradient is non-finite."
            )

        scale_reference = float(stage_initial_obj)
        stage_initial_gap = self._simplex_frank_wolfe_gap(
            K0, stage_initial_grad
        )
        stage_initial_rel_gap = relative_gap(
            stage_initial_obj, stage_initial_gap, scale_reference
        )

        stage_best_objective = float(stage_initial_obj)
        stage_best_objective_K = K0.copy()
        stage_gap_at_best_objective = float(stage_initial_gap)
        stage_rel_gap_at_best_objective = float(stage_initial_rel_gap)

        stage_best_gap = float(stage_initial_gap)
        stage_best_rel_gap = float(stage_initial_rel_gap)
        stage_best_gap_K = K0.copy()
        stage_objective_at_best_gap = float(stage_initial_obj)

        if execution_mode == "default":
            num_runs = md_default_num_runs
            max_iters_per_run = md_default_max_iters_per_run
            stop_selection = "best-objective"
        else:
            num_runs = 1
            max_iters_per_run = None
            stop_selection = "best-relative-fw-gap"

        selected_K = K0.copy()
        selected_reason = None
        selected_label = None

        for run_index in range(num_runs):
            if run_index == 0:
                K_init = K0.copy()
                run_type = "initial"
                run_label = "initial"
                initialization = "deterministic-warm-start"
            else:
                K_init = stage_best_objective_K.copy()
                run_type = "step-size-restart"
                run_label = f"step-restart-{run_index}"
                initialization = "stage-best-objective"
                total_step_size_restarts += 1

            vprint(
                f"[allocation][optimization][{run_label}] "
                f"starting run={run_index} type={run_type} "
                f"initialization={initialization} groups={G} "
                f"stage_best_target_ratio="
                f"{stage_best_rel_gap / md_gap_tol_rel:.3g}"
            )

            (
                run_selected_K,
                run_best_objective_K,
                run_best_gap_K,
                run_info,
            ) = mirror_descent(
                K_init,
                run_label=run_label,
                scale_reference=scale_reference,
                stage_best_rel_gap_before_run=stage_best_rel_gap,
                total_iterations_before=total_iterations,
                max_iters=max_iters_per_run,
                deadline=deadline,
                stop_selection=stop_selection,
            )

            run_info = dict(run_info)
            run_info.update(
                {
                    "stage": "optimization",
                    "run_index": int(run_index),
                    "run_type": run_type,
                    "run_label": run_label,
                    "initialization": initialization,
                }
            )
            all_run_records.append(run_info)
            total_iterations += int(run_info["iterations"])

            if run_info["best_objective_encountered"] < stage_best_objective:
                stage_best_objective = float(
                    run_info["best_objective_encountered"]
                )
                stage_best_objective_K = run_best_objective_K.copy()
                stage_gap_at_best_objective = float(
                    run_info["gap_at_best_objective"]
                )
                stage_rel_gap_at_best_objective = float(
                    run_info["relative_gap_at_best_objective"]
                )

            if run_info["best_relative_gap_encountered"] < stage_best_rel_gap:
                stage_best_gap = float(run_info["best_gap_encountered"])
                stage_best_rel_gap = float(
                    run_info["best_relative_gap_encountered"]
                )
                stage_best_gap_K = run_best_gap_K.copy()
                stage_objective_at_best_gap = float(
                    run_info["objective_at_best_gap"]
                )

            run_final_eta = run_info.get("final_accepted_step_size", None)
            run_final_eta_text = (
                "none" if run_final_eta is None else f"{run_final_eta:.3e}"
            )
            vprint(
                f"[allocation][optimization][{run_label}][done] "
                f"reason={run_info['termination_reason']} "
                f"converged={run_info['converged']} "
                f"iterations={run_info['iterations']} "
                f"objective={run_info['objective']:.8e} "
                f"rel_FW_gap={run_info['relative_frank_wolfe_gap']:.3e} "
                f"run_best_target_ratio="
                f"{run_info['best_relative_gap_encountered'] / md_gap_tol_rel:.3g} "
                f"stage_best_target_ratio="
                f"{stage_best_rel_gap / md_gap_tol_rel:.3g} "
                f"final_eta={run_final_eta_text} "
                f"trial_evals={run_info.get('objective_trial_evaluations', 0)} "
                f"rejected_trials="
                f"{run_info.get('rejected_backtracking_trials', 0)}"
            )

            selected_K = run_selected_K.copy()
            selected_reason = str(run_info["termination_reason"])
            selected_label = str(run_info["returned_solution_selection"])

            if run_info["converged"]:
                selected_K = stage_best_gap_K.copy()
                selected_reason = "frank_wolfe_gap"
                selected_label = "best-relative-fw-gap"
                break

            if selected_reason in {
                "time_limit",
                "nonfinite_objective",
                "nonfinite_gradient",
                "nonfinite_iterate",
                "line_search_failed",
            }:
                selected_K = stage_best_gap_K.copy()
                selected_label = "best-relative-fw-gap"
                break

        if selected_reason is None:
            selected_reason = "max_iters"

        if execution_mode == "default" and selected_reason == "max_iters":
            selected_K = stage_best_objective_K.copy()
            selected_label = "best-objective"
        elif execution_mode in {"until-converged", "user-selected"}:
            selected_K = stage_best_gap_K.copy()
            selected_label = "best-relative-fw-gap"

        final_obj, final_grad = eval_obj_and_grad(selected_K)
        final_gap = self._simplex_frank_wolfe_gap(selected_K, final_grad)
        final_rel_gap = relative_gap(final_obj, final_gap, scale_reference)
        final_converged = bool(final_rel_gap <= md_gap_tol_rel)

        if final_converged:
            final_reason = "frank_wolfe_gap"
            selected_label = "best-relative-fw-gap"
        else:
            final_reason = selected_reason
            if (
                execution_mode == "user-selected"
                and deadline is not None
                and time.perf_counter() >= deadline
            ):
                final_reason = "time_limit"

        solver_elapsed = elapsed_time()
        total_line_search_trial_attempts = int(
            sum(
                int(run.get("line_search_trial_attempts", 0))
                for run in all_run_records
            )
        )
        total_objective_trial_evaluations = int(
            sum(
                int(run.get("objective_trial_evaluations", 0))
                for run in all_run_records
            )
        )
        total_rejected_backtracking_trials = int(
            sum(
                int(run.get("rejected_backtracking_trials", 0))
                for run in all_run_records
            )
        )

        convergence_info = {
            "converged": final_converged,
            "convergence_reason": final_reason,
            "returned_solution_selection": selected_label,
            "md_execution_mode": execution_mode,
            "md_max_time": md_max_time,
            "max_iters_per_run": (
                md_default_max_iters_per_run
                if execution_mode == "default"
                else None
            ),
            "default_num_runs": (
                md_default_num_runs
                if execution_mode == "default"
                else None
            ),
            "elapsed_time": float(solver_elapsed),
            "iterations": int(total_iterations),
            "total_iterations": int(total_iterations),
            "objective": float(final_obj),
            "frank_wolfe_gap": float(final_gap),
            "relative_frank_wolfe_gap": float(final_rel_gap),
            "md_gap_tol_rel": float(md_gap_tol_rel),
            "best_objective_encountered": float(stage_best_objective),
            "gap_at_best_objective": float(stage_gap_at_best_objective),
            "relative_gap_at_best_objective": float(
                stage_rel_gap_at_best_objective
            ),
            "best_gap_encountered": float(stage_best_gap),
            "best_relative_gap_encountered": float(stage_best_rel_gap),
            "objective_at_best_gap": float(stage_objective_at_best_gap),
            "pre_pruning_enabled": bool(enable_pre_pruning),
            "prune_tolerance": float(prune_tol),
            "num_groups_initial": int(num_groups_initial),
            "num_groups_after_pre_pruning": int(
                num_groups_after_pre_pruning
            ),
            "num_groups_after_post_pruning": int(
                num_groups_after_pre_pruning
            ),
            "post_pruning_applied": False,
            "post_pruning_changed_pool": False,
            "num_step_size_restarts": int(total_step_size_restarts),
            "num_random_restarts": 0,
            "denominator_regularization": float(
                md_denominator_epsilon
            ),
            "incidence_matrix_nnz": int(incidence_matrix.nnz),
            "step_size_strategy": "monotonic-backtracking",
            "backtrack_factor": float(md_backtrack_factor),
            "growth_factor": float(md_growth_factor),
            "max_backtracking_trials": int(md_max_backtracking_trials),
            "line_search_trial_attempts": int(
                total_line_search_trial_attempts
            ),
            "objective_trial_evaluations": int(
                total_objective_trial_evaluations
            ),
            "rejected_backtracking_trials": int(
                total_rejected_backtracking_trials
            ),
            "verbose_progress_interval": float(md_verbose_interval),
            "runs": all_run_records,
        }

        vprint(
            "[allocation][done] "
            f"converged={final_converged} reason={final_reason} "
            f"selection={selected_label} "
            f"elapsed={solver_elapsed:.2f}s "
            f"total_iter={total_iterations} "
            f"objective={final_obj:.8e} "
            f"rel_FW_gap={final_rel_gap:.3e} "
            f"target={md_gap_tol_rel:.3e} "
            f"target_ratio={final_rel_gap / md_gap_tol_rel:.3g} "
            f"stage_best_target_ratio="
            f"{stage_best_rel_gap / md_gap_tol_rel:.3g} "
            f"trial_evals={total_objective_trial_evaluations} "
            f"rejected_trials={total_rejected_backtracking_trials}"
        )

        raw = B * selected_K
        reps = self._round_continuous_allocation(
            raw=raw,
            B=B,
            members=members,
            objective_weights=rounding_objective_weights,
            objective_power=p,
            b=b,
            objective_mode=objective_mode,
            truncation_cost=truncation_cost,
        )

        return tokens, members, reps, {
            "relaxed_objective": float(final_obj),
            "num_groups": G,
            "flat_objective": False,
            "convergence": convergence_info,
        }

    def _solve_overlapping_power_with_truncation(
        self,
        tokens,
        members,
        abs_coeffs,
        objective_weights_full,
        objective_power,
        objective_mode,
        b,
        B,
    ):
        """
        Attempt truncation for the overlapping informed allocation.

        Candidate active sets are generated by ranking pool-measurable
        observables by |w_j|. Positive-weight observables absent from every
        supplied setting are excluded from the relaxed objective; their
        contribution is still included in the post-rounded proxy unless prior
        counts already measure them.

        For each candidate active set S:
          - solve the relaxed allocation with inactive objective weights set to zero;
          - use the full group pool;
          - evaluate the final post-rounded energy proxy using the actually
            measured observables.
        """
        M = int(self.num_obs)
        B = int(B)

        abs_coeffs = np.asarray(abs_coeffs, dtype=np.float64).reshape(-1)
        objective_weights_full = np.asarray(objective_weights_full, dtype=np.float64).reshape(-1)
        b = np.asarray(b, dtype=np.float64).reshape(-1)

        if B <= 0 or len(members) == 0:
            self.truncation_info = {
                "attempted": True,
                "selected": False,
                "reason": "zero budget or empty group pool",
            }
            return [], [], np.zeros(0, dtype=np.int64)

        # Only observables that occur in at least one supplied setting can
        # influence the relaxed allocation. Positive-weight observables absent
        # from the pool are forced out of the relaxed objective and remain in
        # the post-rounded truncation/statistical diagnostics as appropriate.
        measurable_from_pool = np.zeros(M, dtype=bool)
        for mem in members:
            measurable_from_pool[np.asarray(mem, dtype=np.int32)] = True

        positive = abs_coeffs > 0.0
        structurally_unmeasurable_positive = positive & ~measurable_from_pool

        order = np.argsort(-abs_coeffs, kind="mergesort")
        optimizable_positive_order = order[
            positive[order] & measurable_from_pool[order]
        ]

        if not np.any(positive):
            toks, mems, reps, alloc_info = self._solve_overlapping_power_with_priors(
                tokens,
                members,
                objective_weights_full,
                objective_power,
                b,
                B,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
                rounding_objective_weights=objective_weights_full,
            )

            self.truncation_info = {
                "attempted": True,
                "selected": False,
                "reason": "all coefficients are zero",
                "allocation_info": alloc_info,
            }

            return toks, mems, reps

        if optimizable_positive_order.size == 0:
            objective_weights_trial = np.zeros_like(objective_weights_full)

            toks, mems, reps, alloc_info = self._solve_overlapping_power_with_priors(
                tokens,
                members,
                objective_weights_trial,
                objective_power,
                b,
                B,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
                rounding_objective_weights=objective_weights_full,
            )

            new_counts = self._counts_from_allocation(mems, reps)
            total_proxy, stat_proxy, trunc_bias, measured = (
                self._energy_proxy_from_counts(
                    abs_coeffs=abs_coeffs,
                    objective_weights=objective_weights_full,
                    objective_power=objective_power,
                    objective_mode=objective_mode,
                    b=b,
                    new_counts=new_counts,
                )
            )

            num_truncated_positive = int(
                np.count_nonzero(positive & ~measured)
            )

            self.truncation_info = {
                "attempted": True,
                "selected": False,
                "selected_objective_truncation": False,
                "actual_truncation_after_rounding": bool(
                    num_truncated_positive > 0
                ),
                "reason": (
                    "no positive-weight observable is measurable from the pool"
                ),
                "num_structurally_unmeasurable_positive_observables": int(
                    np.count_nonzero(structurally_unmeasurable_positive)
                ),
                "num_truncated_positive_observables": int(
                    num_truncated_positive
                ),
                "selected_active_size": 0,
                "no_truncation_active_size": 0,
                "num_candidates": 0,
                "num_measured_observables": int(np.count_nonzero(measured)),
                "stat_proxy": float(stat_proxy),
                "trunc_bias": float(trunc_bias),
                "total_proxy": float(total_proxy),
                "selected_allocation_info": alloc_info,
                "records": [],
            }

            return toks, mems, reps

        candidate_sizes = self._truncation_candidate_sizes(
            int(optimizable_positive_order.size)
        )

        best = None
        records = []

        for candidate_id, m in enumerate(candidate_sizes):
            m = int(m)

            active = np.zeros(M, dtype=bool)
            active[optimizable_positive_order[:m]] = True

            objective_weights_trial = np.zeros_like(objective_weights_full)
            objective_weights_trial[active] = objective_weights_full[active]

            toks, mems, reps, alloc_info = self._solve_overlapping_power_with_priors(
                tokens,
                members,
                objective_weights_trial,
                objective_power,
                b,
                B,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
                # During truncation, marginal rounding is allowed to optimize
                # the final post-rounded proxy rather than only the active
                # relaxed objective.
                rounding_objective_weights=objective_weights_full,
            )

            new_counts = self._counts_from_allocation(mems, reps)

            total_proxy, stat_proxy, trunc_bias, measured = (
                self._energy_proxy_from_counts(
                    abs_coeffs=abs_coeffs,
                    objective_weights=objective_weights_full,
                    objective_power=objective_power,
                    objective_mode=objective_mode,
                    b=b,
                    new_counts=new_counts,
                )
            )

            num_truncated_positive = int(np.count_nonzero(positive & ~measured))

            convergence_info = alloc_info.get("convergence", None)

            record = {
                "candidate_id": int(candidate_id),
                "active_size": int(m),
                "num_groups_after_pruning": int(len(mems)),
                "num_groups_with_nonzero_reps": int(np.count_nonzero(reps > 0)),
                "num_measured_observables": int(np.count_nonzero(measured)),
                "num_truncated_positive_observables": int(num_truncated_positive),
                "stat_proxy": float(stat_proxy),
                "trunc_bias": float(trunc_bias),
                "total_proxy": float(total_proxy),
                "allocation_convergence": convergence_info,
            }
            records.append(record)

            if best is None or total_proxy < best["total_proxy"]:
                best = {
                    "tokens": toks,
                    "members": mems,
                    "reps": reps,
                    "active_size": int(m),
                    "total_proxy": float(total_proxy),
                    "stat_proxy": float(stat_proxy),
                    "trunc_bias": float(trunc_bias),
                    "num_measured_observables": int(np.count_nonzero(measured)),
                    "num_truncated_positive_observables": int(num_truncated_positive),
                    "allocation_info": alloc_info,
                    "candidate_id": int(candidate_id),
                }

        if best is None:
            self.truncation_info = {
                "attempted": True,
                "selected": False,
                "reason": "no candidate allocation was produced",
            }
            return [], [], np.zeros(0, dtype=np.int64)

        no_trunc_size = int(optimizable_positive_order.size)
        selected_objective_truncation = best["active_size"] < no_trunc_size
        actual_truncation_after_rounding = best["num_truncated_positive_observables"] > 0

        self.truncation_info = {
            "attempted": True,

            # True if the selected candidate used fewer active observables than
            # the full positive-coefficient set.
            "selected": bool(selected_objective_truncation),

            "selected_objective_truncation": bool(selected_objective_truncation),
            "actual_truncation_after_rounding": bool(actual_truncation_after_rounding),
            "num_truncated_positive_observables": int(
                best["num_truncated_positive_observables"]
            ),
            "num_structurally_unmeasurable_positive_observables": int(
                np.count_nonzero(structurally_unmeasurable_positive)
            ),

            "selected_candidate_id": int(best["candidate_id"]),
            "selected_active_size": int(best["active_size"]),
            "no_truncation_active_size": int(no_trunc_size),
            "num_candidates": int(len(candidate_sizes)),
            "num_measured_observables": int(best["num_measured_observables"]),
            "stat_proxy": float(best["stat_proxy"]),
            "trunc_bias": float(best["trunc_bias"]),
            "total_proxy": float(best["total_proxy"]),
            "selected_allocation_info": best["allocation_info"],
            "records": records,
        }

        return best["tokens"], best["members"], best["reps"]

    # ------------------------------------------------------------------
    # Public allocation entry point
    # ------------------------------------------------------------------

    def allocate_budget(self):
        """
        Offline allocation; fills settings_dict/settings_buffer and updates:

          - N_hits
          - N_hits_pairs

        Semantics:
          - prior_counts[j] = already available reusable samples for Pauli j
          - total_rounds    = new rounds to allocate now

        Modes:
          - uninformed allocation:
                uniform over groups;

          - informed non-overlap:
                exact convex solve for the power-law objective;

          - informed overlap without truncation:
                mirror descent on the relaxed overlapping power-law objective;

          - informed overlap with truncation:
                scan candidate active sets, solve the overlapping allocation
                with inactive weights set to zero, then choose the candidate
                minimizing the post-rounded energy proxy.
        """
        B = int(self.total_rounds)

        self._clear_new_scheme_state()

        self.truncation_info = {
            "attempted": False,
            "selected": False,
        }

        self.allocation_info = {
            "attempted": False,
            "mode": None,
        }

        abs_coeffs, objective_weights, objective_power, objective_mode = (
            self._energy_objective_params()
        )

        if hasattr(self, "prior_counts"):
            b = np.asarray(self.prior_counts, dtype=np.float64).reshape(-1)
        else:
            b = np.zeros(int(self.num_obs), dtype=np.float64)

        if b.shape != (self.num_obs,):
            raise ValueError(
                f"prior_counts must have shape ({self.num_obs},), got {b.shape}."
            )

        if np.any(b < 0.0):
            raise ValueError("prior_counts must be nonnegative.")

        allocation_pool = getattr(
            self,
            "_allocation_cliques_pool_override",
            self.cliques_pool,
        )

        if allocation_pool is None:
            raise ValueError("The allocation cliques pool cannot be None.")

        if B <= 0 or len(allocation_pool) == 0:
            reason = "zero_budget" if B <= 0 else "empty_group_pool"
            self._store_post_rounded_proxy_info(
                abs_coeffs=abs_coeffs,
                objective_weights=objective_weights,
                objective_power=objective_power,
                objective_mode=objective_mode,
                b=b,
                members=[],
                reps=np.zeros(0, dtype=np.int64),
                reason=reason,
            )
            return

        members = allocation_pool
        tokens = [encode_setting_token(g) for g in members]

        G = len(members)
        if G == 0:
            return

        informed_allocation = bool(getattr(self, "informed_allocation", True))

        if not informed_allocation:
            reps = self._uniform_reps(G, B)
            self._commit_allocation(tokens, members, reps)

            self.allocation_info = {
                "attempted": True,
                "mode": "uniform",
                "num_groups": int(G),
            }

            self._store_post_rounded_proxy_info(
                abs_coeffs=abs_coeffs,
                objective_weights=objective_weights,
                objective_power=objective_power,
                objective_mode=objective_mode,
                b=b,
                members=members,
                reps=reps,
            )
            return

        is_overlapping = bool(getattr(self, "is_overlapping", False))

        if not is_overlapping:
            raw = self._solve_nonoverlap_power_with_priors(
                members=members,
                objective_weights=objective_weights,
                objective_power=objective_power,
                b=b,
                B=B,
            )

            reps = self._round_continuous_allocation(
                raw=raw,
                B=B,
                members=members,
                objective_weights=objective_weights,
                objective_power=objective_power,
                b=b,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
            )

            self._commit_allocation(tokens, members, reps)

            self.allocation_info = {
                "attempted": True,
                "mode": "informed_nonoverlap",
                "allocation_objective": objective_mode,
                "objective_power": float(objective_power),
                "num_groups": int(G),
            }

            self._store_post_rounded_proxy_info(
                abs_coeffs=abs_coeffs,
                objective_weights=objective_weights,
                objective_power=objective_power,
                objective_mode=objective_mode,
                b=b,
                members=members,
                reps=reps,
            )
            return

        if bool(getattr(self, "attempt_truncation", False)):
            tokens, members, reps = self._solve_overlapping_power_with_truncation(
                tokens=tokens,
                members=members,
                abs_coeffs=abs_coeffs,
                objective_weights_full=objective_weights,
                objective_power=objective_power,
                objective_mode=objective_mode,
                b=b,
                B=B,
            )

            self.allocation_info = {
                "attempted": True,
                "mode": "informed_overlap_with_truncation",
                "allocation_objective": objective_mode,
                "objective_power": float(objective_power),
                "truncation_info": self.truncation_info,
            }

        else:
            tokens, members, reps, alloc_info = self._solve_overlapping_power_with_priors(
                tokens_in=tokens,
                members_in=members,
                objective_weights=objective_weights,
                objective_power=objective_power,
                b=b,
                B=B,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
                rounding_objective_weights=objective_weights,
            )

            self.allocation_info = {
                "attempted": True,
                "mode": "informed_overlap",
                "allocation_objective": objective_mode,
                "objective_power": float(objective_power),
                **alloc_info,
            }

        self._commit_allocation(tokens, members, reps)

        self._store_post_rounded_proxy_info(
            abs_coeffs=abs_coeffs,
            objective_weights=objective_weights,
            objective_power=objective_power,
            objective_mode=objective_mode,
            b=b,
            members=members,
            reps=reps,
        )
