import numpy as np

from shadowgrouping_v2.helper_functions import encode_setting_token

class _AllocationMixin:
    """
    Offline budget-allocation backend for ShadowGrouping energy-estimation schemes.

    Assumes the concrete class provides:
      - self.obs
      - self.num_obs
      - self.num_qubits
      - self.w
      - self.total_rounds
      - self.cliques_pool
      - self.is_overlapping
      - self.settings_dict
      - self.settings_buffer
      - self.seen_settings
      - self._is_hit_rows_used
      - self.N_hits
      - self.N_hits_pairs
      - self._append_is_hit_row(...)

    Optional concrete-class attributes:
      - self.informed_allocation
      - self.prior_counts
      - self.allocation_objective
      - self.attempt_truncation
      - self.rounding_strategy
      - self.md_gap_tol_rel
      - self.truncation_num_candidates
      - self.truncation_min_active

    Energy-estimation objectives
    ----------------------------
    The allocation objective is written as

        sum_j a_j / N_j^p,

    where N_j is the effective number of samples for Pauli string j.

    Supported allocation objectives:

      1) allocation_objective = "variance"

            a_j = |w_j|^2
            p   = 1

         This corresponds to the usual diagonal variance proxy

            sum_j |w_j|^2 / N_j.

      2) allocation_objective = "bernstein_l1"

            a_j = |w_j|
            p   = 1/2

         This corresponds to the ShadowGrouping/Bernstein-style quantity

            sum_j |w_j| / sqrt(N_j).

    Truncation convention
    ---------------------
    If self.attempt_truncation is True, candidate active sets are generated by
    ranking Pauli strings by |w_j|. The allocation objective ignores inactive
    Pauli strings by setting their optimization weights to zero.

    The full group pool is still used, so inactive Pauli strings may still be
    measured incidentally.

    Candidate truncation cuts are evaluated after integer rounding.

      - variance mode:

            total_proxy =
                sum_{measured j} |w_j|^2 / N_j
                +
                (sum_{unmeasured j} |w_j|)^2

      - bernstein_l1 mode:

            total_proxy =
                sum_{measured j} |w_j| / sqrt(N_j)
                +
                sum_{unmeasured j} |w_j|

    Rounding strategies
    -------------------
    The concrete class may set

        self.rounding_strategy = "largest_fraction"

    or

        self.rounding_strategy = "marginal".

    "largest_fraction" floors the relaxed allocation and gives leftover shots
    to the groups with the largest fractional parts.

    "marginal" floors the relaxed allocation and gives leftover shots one at a
    time to the group with the largest finite-difference decrease in the current
    objective. Selection is with replacement.

    Relaxed overlapping solver accuracy
    -----------------------------------
    The relaxed overlapping allocation problem is solved approximately using
    exponentiated-gradient mirror descent on the simplex.

    The convergence certificate is the relative Frank-Wolfe gap,

        gap_rel = gap_FW / max(abs(objective), abs(initial_objective), 1e-300),

    where

        gap_FW = <grad, K> - min_g grad_g.

    For convex minimization over the simplex, gap_FW upper-bounds the relaxed
    suboptimality F(K) - F(K*).

    The concrete class may provide one user-facing accuracy parameter:

        self.md_gap_tol_rel

    Recommended values:
        1e-3 : fast optimization
        1e-4 : default
        1e-6 : high accuracy

    All other mirror-descent parameters are hard-coded internally.
    """

    # ------------------------------------------------------------------
    # Objective setup
    # ------------------------------------------------------------------

    def _energy_objective_params(self):
        """
        Return the energy-estimation objective parameters.

        Returns
        -------
        abs_coeffs : np.ndarray
            |w_j|.

        objective_weights : np.ndarray
            a_j in the power-law objective sum_j a_j / N_j^p.

        objective_power : float
            p in the power-law objective.

        objective_mode : str
            Canonical objective name: "variance" or "bernstein_l1".
        """
        abs_coeffs = np.abs(np.asarray(self.w, dtype=np.float64)).reshape(-1)

        if abs_coeffs.shape != (self.num_obs,):
            raise ValueError(
                f"self.w must have shape ({self.num_obs},), got {abs_coeffs.shape}."
            )

        mode = str(getattr(self, "allocation_objective", "variance")).lower()

        variance_aliases = {
            "variance",
            "l2",
            "l2_squared",
            "total_variance",
            "diagonal_variance",
        }

        bernstein_aliases = {
            "bernstein_l1",
            "l1",
            "shadow_l1",
            "shadowgrouping_l1",
            "bernstein",
        }

        if mode in variance_aliases:
            objective_weights = abs_coeffs * abs_coeffs
            objective_power = 1.0
            objective_mode = "variance"

        elif mode in bernstein_aliases:
            objective_weights = abs_coeffs.copy()
            objective_power = 0.5
            objective_mode = "bernstein_l1"

        else:
            raise ValueError(
                "allocation_objective must be one of "
                "'variance' or 'bernstein_l1'. "
                f"Got {mode!r}."
            )

        return abs_coeffs, objective_weights, objective_power, objective_mode

    @staticmethod
    def _required_obs_mask(objective_weights: np.ndarray, b: np.ndarray) -> np.ndarray:
        """
        Observables that must remain newly coverable by the allocated scheme
        because they have positive objective weight and zero prior counts.

        This is only used to keep the relaxed continuous objective well-defined.
        It does not force the final rounded integer allocation to measure every
        such observable.
        """
        return (objective_weights > 0.0) & (b <= 0.0)

    @staticmethod
    def _simplex_frank_wolfe_gap(K: np.ndarray, grad: np.ndarray) -> float:
        """
        Frank-Wolfe dual gap for minimization over the probability simplex.

        For convex differentiable F over the simplex,

            gap_FW(K) = <grad, K> - min_g grad_g

        satisfies

            F(K) - F(K*) <= gap_FW(K).
        """
        K = np.asarray(K, dtype=np.float64)
        grad = np.asarray(grad, dtype=np.float64)

        if K.size == 0:
            return 0.0

        gap = float(np.dot(grad, K) - np.min(grad))
        return max(0.0, gap)

    @staticmethod
    def _safe_prune_with_priors(tokens, members, K, objective_weights, b, tol):
        """
        Drop tiny-K overlapping groups only if doing so does not remove the last
        new-coverage route for any observable with positive objective weight and
        zero prior counts.

        Observables with positive prior counts may be left uncovered by the new
        scheme, since their denominator remains finite through b_j.
        """
        G = len(members)
        if G == 0:
            return tokens, members, K

        M = len(objective_weights)
        required = _AllocationMixin._required_obs_mask(objective_weights, b)

        cc = np.zeros(M, dtype=np.int32)
        for gg in range(G):
            req_mem = members[gg][required[members[gg]]]
            if req_mem.size > 0:
                cc[req_mem] += 1

        keep = np.ones(G, dtype=bool)

        for gg in np.argsort(K, kind="mergesort"):
            if K[gg] >= tol:
                break

            mem = members[gg]
            req_mem = mem[required[mem]]

            if req_mem.size == 0:
                keep[gg] = False
                continue

            if np.all(cc[req_mem] > 1):
                cc[req_mem] -= 1
                keep[gg] = False

        # Avoid returning an empty group pool.
        if not np.any(keep):
            keep[int(np.argmax(K))] = True

        if np.all(keep):
            return tokens, members, K

        new_tokens = [t for t, k in zip(tokens, keep) if k]
        new_members = [m for m, k in zip(members, keep) if k]
        new_K = K[keep]

        sK = float(np.sum(new_K))
        if sK <= 0.0:
            new_K = np.full(len(new_members), 1.0 / len(new_members), dtype=np.float64)
        else:
            new_K = new_K / sK

        return new_tokens, new_members, new_K

    # ------------------------------------------------------------------
    # Non-overlapping informed allocation
    # ------------------------------------------------------------------

    @staticmethod
    def _solve_nonoverlap_power_with_priors(
        members,
        objective_weights,
        objective_power,
        b,
        B,
        max_outer=80,
        max_inner=80,
    ):
        """
        Solve the exact convex non-overlapping informed allocation:

            minimize_x  sum_g sum_{j in g} a_j / (b_j + x_g)^p
            subject to  x_g >= 0,  sum_g x_g = B.

        Returns
        -------
        raw : np.ndarray
            Real-valued group allocations.
        """
        G = len(members)
        raw = np.zeros(G, dtype=np.float64)

        if B <= 0 or G == 0:
            return raw

        objective_weights = np.asarray(objective_weights, dtype=np.float64)
        b = np.asarray(b, dtype=np.float64)
        p = float(objective_power)

        if not np.any(objective_weights > 0.0):
            raw[:] = float(B) / float(G)
            return raw

        a_groups = [np.asarray(objective_weights[mem], dtype=np.float64) for mem in members]
        b_groups = [np.asarray(b[mem], dtype=np.float64) for mem in members]

        def group_x_for_lambda(ag, bg, lam):
            positive = ag > 0.0

            if ag.size == 0 or not np.any(positive):
                return 0.0

            if np.any((bg[positive] <= 0.0)):
                phi0 = np.inf
            else:
                phi0 = float(
                    p * np.sum(ag[positive] / (bg[positive] ** (p + 1.0)))
                )

            if np.isfinite(phi0) and phi0 <= lam:
                return 0.0

            lo = 0.0
            hi = 1.0

            while True:
                denom = bg + hi
                phi_hi = float(p * np.sum(ag / (denom ** (p + 1.0))))
                if phi_hi <= lam:
                    break
                hi *= 2.0

            for _ in range(max_inner):
                mid = 0.5 * (lo + hi)
                denom = bg + mid
                phi_mid = float(p * np.sum(ag / (denom ** (p + 1.0))))

                if phi_mid > lam:
                    lo = mid
                else:
                    hi = mid

            return hi

        def total_x_for_lambda(lam):
            s = 0.0
            xs = np.empty(G, dtype=np.float64)

            for gg in range(G):
                xg = group_x_for_lambda(a_groups[gg], b_groups[gg], lam)
                xs[gg] = xg
                s += xg

            return s, xs

        lam_hi = 1.0
        s_hi, _ = total_x_for_lambda(lam_hi)

        while s_hi > B:
            lam_hi *= 2.0
            s_hi, _ = total_x_for_lambda(lam_hi)

        lam_lo = lam_hi
        while True:
            lam_lo *= 0.5
            s_lo, _ = total_x_for_lambda(lam_lo)

            if s_lo >= B:
                break

            if lam_lo < 1e-300:
                break

        best_x = None

        for _ in range(max_outer):
            lam_mid = 0.5 * (lam_lo + lam_hi)
            s_mid, x_mid = total_x_for_lambda(lam_mid)

            best_x = x_mid

            if s_mid >= B:
                lam_lo = lam_mid
            else:
                lam_hi = lam_mid

        if best_x is None:
            _, best_x = total_x_for_lambda(lam_hi)

        return best_x

    # ------------------------------------------------------------------
    # Rounding helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _round_raw_allocation_largest_fraction(raw: np.ndarray, B: int) -> np.ndarray:
        """
        Floor a real-valued allocation and distribute leftover shots to the
        largest fractional parts.
        """
        raw = np.asarray(raw, dtype=np.float64)
        G = int(raw.size)

        if G == 0:
            return np.zeros(0, dtype=np.int64)

        if B <= 0:
            return np.zeros(G, dtype=np.int64)

        raw = np.maximum(raw, 0.0)

        s_raw = float(np.sum(raw))
        if s_raw > 0.0:
            raw = raw * (float(B) / s_raw)

        reps = np.floor(raw).astype(np.int64)
        leftover = int(B) - int(np.sum(reps))

        if leftover < 0:
            raise RuntimeError(
                "Floor-rounded allocation exceeds the total budget. "
                "This should not happen unless raw allocation is inconsistent."
            )

        if leftover > 0:
            frac = raw - reps
            order = np.argsort(-frac, kind="mergesort")

            for i in range(leftover):
                reps[order[i % G]] += 1

        return reps

    def _round_raw_allocation_marginal(
        self,
        raw: np.ndarray,
        B: int,
        members,
        objective_weights: np.ndarray,
        objective_power: float,
        b: np.ndarray,
        *,
        truncation_mode: bool = False,
        objective_mode: str = "variance",
        truncation_cost: np.ndarray | None = None,
        zero_count_marginal: float = np.inf,
    ) -> np.ndarray:
        """
        Marginal-gain rounding for the leftover budget.

        For a measured observable with effective count N_j > 0, the exact
        finite-difference gain is

            a_j * [N_j^{-p} - (N_j + 1)^{-p}].

        Without truncation, zero-count positive-weight observables receive
        infinite marginal value, reflecting the singular objective.

        With truncation:
          - bernstein_l1 mode uses zero first-sample gain;
          - variance mode uses the exact group-level finite difference of

                variance + truncation_bias^2.
        """
        raw = np.asarray(raw, dtype=np.float64)
        objective_weights = np.asarray(objective_weights, dtype=np.float64)
        b = np.asarray(b, dtype=np.float64)
        p = float(objective_power)

        if truncation_cost is None:
            truncation_cost = np.zeros_like(objective_weights)
        else:
            truncation_cost = np.asarray(truncation_cost, dtype=np.float64)

        G = int(raw.size)
        M = int(self.num_obs)

        if G == 0:
            return np.zeros(0, dtype=np.int64)

        if B <= 0:
            return np.zeros(G, dtype=np.int64)

        raw = np.maximum(raw, 0.0)

        s_raw = float(np.sum(raw))
        if s_raw > 0.0:
            raw = raw * (float(B) / s_raw)

        reps = np.floor(raw).astype(np.int64)
        leftover = int(B) - int(np.sum(reps))

        if leftover < 0:
            raise RuntimeError(
                "Floor-rounded allocation exceeds the total budget. "
                "This should not happen unless raw allocation is inconsistent."
            )

        if leftover == 0:
            return reps

        counts = self._counts_from_allocation(members, reps).astype(np.float64)
        rounding_residual = raw - reps.astype(np.float64)

        positive_weight = objective_weights > 0.0
        objective_mode = str(objective_mode).lower()

        for _ in range(leftover):
            N_eff = b + counts

            marginal_obs = np.zeros(M, dtype=np.float64)

            measured = positive_weight & (N_eff > 0.0)
            if np.any(measured):
                marginal_obs[measured] = objective_weights[measured] * (
                    N_eff[measured] ** (-p)
                    -
                    (N_eff[measured] + 1.0) ** (-p)
                )

            zero_count = positive_weight & (N_eff <= 0.0)

            if not truncation_mode:
                if np.any(zero_count):
                    marginal_obs[zero_count] = zero_count_marginal

                group_scores = np.empty(G, dtype=np.float64)
                for gg in range(G):
                    group_scores[gg] = float(np.sum(marginal_obs[members[gg]]))

            elif objective_mode == "bernstein_l1":
                # First sample changes |w_j| -> |w_j| / sqrt(1) = |w_j|,
                # so the first-sample gain is zero under the linear
                # statistical + truncation-bias proxy.
                if np.any(zero_count):
                    marginal_obs[zero_count] = 0.0

                group_scores = np.empty(G, dtype=np.float64)
                for gg in range(G):
                    group_scores[gg] = float(np.sum(marginal_obs[members[gg]]))

            elif objective_mode == "variance":
                # Exact group-level finite difference of
                #
                #   stat + T^2,
                #
                # where T = sum_{unmeasured j} |w_j|.
                tail_mask = (truncation_cost > 0.0) & (N_eff <= 0.0)
                T = float(np.sum(truncation_cost[tail_mask]))

                group_scores = np.empty(G, dtype=np.float64)

                for gg in range(G):
                    mem = members[gg]

                    score = float(np.sum(marginal_obs[mem]))

                    zero_mem = mem[(truncation_cost[mem] > 0.0) & (N_eff[mem] <= 0.0)]

                    if zero_mem.size > 0:
                        Cg = float(np.sum(truncation_cost[zero_mem]))
                        Qg = float(np.sum(truncation_cost[zero_mem] ** 2))

                        # Gain from removing those zero-count terms from the
                        # truncation tail while adding their one-sample variance.
                        score += 2.0 * T * Cg - Cg * Cg - Qg

                    group_scores[gg] = score

            else:
                raise ValueError(f"Unknown objective_mode={objective_mode!r}.")

            best_score = float(np.max(group_scores))
            candidates = np.flatnonzero(group_scores == best_score)

            if candidates.size == 1:
                g_best = int(candidates[0])
            else:
                local = rounding_residual[candidates]
                g_best = int(candidates[int(np.argmax(local))])

            reps[g_best] += 1
            rounding_residual[g_best] -= 1.0

            counts[members[g_best]] += 1.0

        return reps

    def _round_continuous_allocation(
        self,
        raw: np.ndarray,
        B: int,
        members,
        objective_weights: np.ndarray,
        objective_power: float,
        b: np.ndarray,
        *,
        truncation_mode: bool = False,
        objective_mode: str = "variance",
        truncation_cost: np.ndarray | None = None,
    ) -> np.ndarray:
        """
        Dispatch integer rounding according to self.rounding_strategy.
        """
        strategy = str(getattr(self, "rounding_strategy", "largest_fraction")).lower()

        if strategy == "largest_fraction":
            return self._round_raw_allocation_largest_fraction(raw, B)

        if strategy == "marginal":
            return self._round_raw_allocation_marginal(
                raw=raw,
                B=B,
                members=members,
                objective_weights=objective_weights,
                objective_power=objective_power,
                b=b,
                truncation_mode=truncation_mode,
                objective_mode=objective_mode,
                truncation_cost=truncation_cost,
            )

        raise ValueError(
            "rounding_strategy must be either 'largest_fraction' or 'marginal'. "
            f"Got {strategy!r}."
        )

    @staticmethod
    def _uniform_reps(G: int, B: int) -> np.ndarray:
        """
        Uniform integer allocation over G groups.
        """
        G = int(G)
        B = int(B)

        if G <= 0:
            return np.zeros(0, dtype=np.int64)

        if B <= 0:
            return np.zeros(G, dtype=np.int64)

        reps = np.full(G, B // G, dtype=np.int64)
        leftover = B - int(np.sum(reps))

        for i in range(leftover):
            reps[i % G] += 1

        return reps

    # ------------------------------------------------------------------
    # State updates and diagnostics
    # ------------------------------------------------------------------

    def _clear_new_scheme_state(self):
        """
        Clear only the state associated with the newly allocated scheme.
        """
        self.settings_dict = {}
        self.settings_buffer = {}
        self.seen_settings = set()
        self._is_hit_rows_used = 0
        self.N_hits[:] = 0

        if hasattr(self, "N_hits_pairs"):
            self.N_hits_pairs[:] = 0

    def _commit_allocation(self, tokens, members, reps):
        """
        Commit a new integer allocation to settings_dict/settings_buffer and
        update N_hits and N_hits_pairs.
        """
        M = int(self.num_obs)

        for gg in range(len(members)):
            r = int(reps[gg])
            if r <= 0:
                continue

            tok = tokens[gg]
            clique = members[gg]

            self.settings_dict[tok] = self.settings_dict.get(tok, 0) + r
            self.settings_buffer[tok] = self.settings_buffer.get(tok, 0) + r
            self.seen_settings.add(tok)

            row = np.zeros(M, dtype=bool)
            row[clique] = True
            #self._append_is_hit_row(row)

            self.N_hits[clique] += r

            if hasattr(self, "N_hits_pairs"):
                self.N_hits_pairs[np.ix_(clique, clique)] += r

    def _counts_from_allocation(self, members, reps):
        """
        Compute per-observable newly allocated counts for a candidate allocation
        without committing it.
        """
        counts = np.zeros(int(self.num_obs), dtype=np.int64)

        for gg in range(len(members)):
            r = int(reps[gg])
            if r <= 0:
                continue
            counts[members[gg]] += r

        return counts

    @staticmethod
    def _energy_proxy_from_counts(
        abs_coeffs,
        objective_weights,
        objective_power,
        objective_mode,
        b,
        new_counts,
    ):
        """
        Evaluate the post-rounded energy-estimation proxy.

        variance mode:
            total = sum_measured |w_j|^2 / N_j
                    +
                    (sum_unmeasured |w_j|)^2

        bernstein_l1 mode:
            total = sum_measured |w_j| / sqrt(N_j)
                    +
                    sum_unmeasured |w_j|
        """
        abs_coeffs = np.asarray(abs_coeffs, dtype=np.float64)
        objective_weights = np.asarray(objective_weights, dtype=np.float64)
        b = np.asarray(b, dtype=np.float64)
        new_counts = np.asarray(new_counts, dtype=np.float64)
        p = float(objective_power)

        N_eff = b + new_counts
        measured = N_eff > 0.0

        stat_proxy = 0.0
        if np.any(measured):
            stat_proxy = float(
                np.sum(objective_weights[measured] / (N_eff[measured] ** p))
            )

        trunc_bias = float(np.sum(abs_coeffs[~measured]))

        objective_mode = str(objective_mode).lower()

        if objective_mode == "variance":
            total_proxy = stat_proxy + trunc_bias * trunc_bias

        elif objective_mode == "bernstein_l1":
            total_proxy = stat_proxy + trunc_bias

        else:
            raise ValueError(f"Unknown objective_mode={objective_mode!r}.")

        return total_proxy, stat_proxy, trunc_bias, measured

    # ------------------------------------------------------------------
    # Truncation candidate generation
    # ------------------------------------------------------------------

    def _truncation_candidate_sizes(self, num_positive: int) -> np.ndarray:
        """
        Candidate numbers of active observables to keep.

        Uses a logarithmic-scale scan. The largest candidate is num_positive,
        corresponding to no objective-level truncation among positive-weight
        Pauli strings.

        Optional concrete-class attributes:
          - self.truncation_num_candidates
          - self.truncation_min_active
        """
        num_positive = int(num_positive)

        if num_positive <= 0:
            return np.zeros(0, dtype=np.int64)

        default_num = min(
            32,
            max(2, int(np.ceil(np.log2(max(num_positive, 2)))) + 1),
        )

        num_candidates = int(getattr(self, "truncation_num_candidates", default_num))
        num_candidates = max(1, num_candidates)

        min_active = int(getattr(self, "truncation_min_active", 1))
        min_active = max(1, min(min_active, num_positive))

        if min_active == num_positive:
            return np.array([num_positive], dtype=np.int64)

        sizes = np.unique(
            np.round(
                np.geomspace(min_active, num_positive, num=num_candidates)
            ).astype(np.int64)
        )

        sizes = sizes[(sizes >= min_active) & (sizes <= num_positive)]

        sizes = np.unique(
            np.concatenate((sizes, np.array([num_positive], dtype=np.int64)))
        )

        return sizes.astype(np.int64, copy=False)

    # ------------------------------------------------------------------
    # Overlapping informed allocation
    # ------------------------------------------------------------------

    def _solve_overlapping_power_with_priors(
        self,
        tokens_in,
        members_in,
        objective_weights,
        objective_power,
        b,
        B,
        *,
        objective_mode: str,
        truncation_cost: np.ndarray | None = None,
        rounding_objective_weights: np.ndarray | None = None,
    ):
        """
        Solve the overlapping informed allocation for a fixed power-law objective:

            minimize_K sum_j a_j / (b_j + B chi_j(K))^p
            subject to K_g >= 0, sum_g K_g = 1.

        The solver is exponentiated-gradient mirror descent on the simplex.
        Convergence is certified using the relative Frank-Wolfe gap.
        """
        # Hard-coded solver parameters.
        md_iters = 1000
        md_restarts = 3
        md_eta0 = 0.5
        md_noise_sigma = 0.35
        eps_chi = 1e-12
        md_min_iters = 25

        md_gap_tol_rel = float(getattr(self, "md_gap_tol_rel", 1e-4))
        if md_gap_tol_rel <= 0.0:
            raise ValueError("md_gap_tol_rel must be positive.")

        B = int(B)
        M = int(self.num_obs)

        tokens = list(tokens_in)
        members = [np.asarray(g, dtype=np.int32) for g in members_in]

        G = len(members)
        if B <= 0 or G == 0:
            return [], [], np.zeros(0, dtype=np.int64), {
                "relaxed_objective": None,
                "num_groups": 0,
                "flat_objective": False,
                "convergence": None,
            }

        objective_weights = np.asarray(objective_weights, dtype=np.float64).reshape(-1)
        b = np.asarray(b, dtype=np.float64).reshape(-1)
        p = float(objective_power)

        if rounding_objective_weights is None:
            rounding_objective_weights = objective_weights
        else:
            rounding_objective_weights = np.asarray(
                rounding_objective_weights, dtype=np.float64
            ).reshape(-1)

        if truncation_cost is None:
            truncation_cost = np.zeros(M, dtype=np.float64)
        else:
            truncation_cost = np.asarray(truncation_cost, dtype=np.float64).reshape(-1)

        if objective_weights.shape != (M,):
            raise ValueError(f"objective_weights must have shape ({M},).")

        if rounding_objective_weights.shape != (M,):
            raise ValueError(f"rounding_objective_weights must have shape ({M},).")

        if truncation_cost.shape != (M,):
            raise ValueError(f"truncation_cost must have shape ({M},).")

        if b.shape != (M,):
            raise ValueError(f"b must have shape ({M},), got {b.shape}.")

        if np.any(objective_weights < -1e-14):
            raise ValueError("Objective weights must be nonnegative.")

        if np.any(rounding_objective_weights < -1e-14):
            raise ValueError("Rounding objective weights must be nonnegative.")

        if np.any(truncation_cost < -1e-14):
            raise ValueError("Truncation costs must be nonnegative.")

        if np.any(b < 0.0):
            raise ValueError("Prior counts must be nonnegative.")

        if p <= 0.0:
            raise ValueError("objective_power must be positive.")

        objective_weights = np.maximum(objective_weights, 0.0)
        rounding_objective_weights = np.maximum(rounding_objective_weights, 0.0)
        truncation_cost = np.maximum(truncation_cost, 0.0)

        if not np.any(objective_weights > 0.0):
            reps = self._uniform_reps(G, B)

            return tokens, members, reps, {
                "relaxed_objective": None,
                "num_groups": G,
                "flat_objective": True,
                "convergence": {
                    "converged": True,
                    "convergence_reason": "flat_objective",
                    "frank_wolfe_gap": 0.0,
                    "relative_frank_wolfe_gap": 0.0,
                    "md_gap_tol_rel": float(md_gap_tol_rel),
                },
            }

        prune_tol = max(1e-8, 0.25 / float(max(B, 1)))
        rng = np.random.default_rng(0)

        # Warm start: for non-overlapping no-prior power-law problems, the
        # natural scaling is x_g ∝ (sum_j a_j)^{1/(p+1)}.
        Wg = np.zeros(G, dtype=np.float64)
        for gg in range(G):
            Wg[gg] = float(np.sum(objective_weights[members[gg]]))

        sg = np.maximum(Wg, 0.0) ** (1.0 / (p + 1.0))

        if float(np.sum(sg)) <= 0.0:
            K0 = np.full(G, 1.0 / G, dtype=np.float64)
        else:
            K0 = (sg / float(np.sum(sg))).astype(np.float64)

        tokens, members, K0 = self._safe_prune_with_priors(
            tokens,
            members,
            K0,
            objective_weights,
            b,
            prune_tol,
        )

        G = len(members)
        if G == 0:
            return [], [], np.zeros(0, dtype=np.int64), {
                "relaxed_objective": None,
                "num_groups": 0,
                "flat_objective": False,
                "convergence": None,
            }

        def eval_obj_and_grad(K):
            chi = np.zeros(M, dtype=np.float64)
            for gg in range(G):
                chi[members[gg]] += K[gg]

            denom = b + B * chi
            denom_safe = np.maximum(denom, eps_chi)

            obj = float(np.sum(objective_weights / (denom_safe ** p)))

            # d/dK_g [a_j / (b_j + B chi_j)^p]
            #   = -B p a_j / (b_j + B chi_j)^(p+1).
            inv = (B * p * objective_weights) / (denom_safe ** (p + 1.0))

            grad = np.empty(G, dtype=np.float64)
            for gg in range(G):
                grad[gg] = -float(np.sum(inv[members[gg]]))

            return obj, grad

        def mirror_descent(K_init):
            K = K_init.copy()

            obj0, grad0 = eval_obj_and_grad(K)
            gap0 = self._simplex_frank_wolfe_gap(K, grad0)

            best_K = K.copy()
            best_obj = float(obj0)
            best_gap = float(gap0)
            best_rel_gap = float(gap0 / max(abs(float(obj0)), 1e-300))
            best_iter = 0

            convergence_reason = "max_iters"

            for t in range(md_iters):
                obj, grad = eval_obj_and_grad(K)
                gap = self._simplex_frank_wolfe_gap(K, grad)

                scale = max(abs(float(obj)), abs(float(obj0)), 1e-300)
                rel_gap = gap / scale

                if obj < best_obj:
                    best_obj = float(obj)
                    best_K = K.copy()
                    best_gap = float(gap)
                    best_rel_gap = float(rel_gap)
                    best_iter = int(t)

                if t >= md_min_iters and rel_gap <= md_gap_tol_rel:
                    convergence_reason = "frank_wolfe_gap"

                    best_obj = float(obj)
                    best_K = K.copy()
                    best_gap = float(gap)
                    best_rel_gap = float(rel_gap)
                    best_iter = int(t)
                    break

                gmax = float(np.max(np.abs(grad))) + 1e-12
                eta = md_eta0 / (np.sqrt(t + 1.0) * gmax)

                step = np.clip(-eta * grad, -50.0, 50.0)

                K *= np.exp(step)
                K = np.maximum(K, 1e-300)
                K /= float(np.sum(K))

            final_obj, final_grad = eval_obj_and_grad(best_K)
            final_gap = self._simplex_frank_wolfe_gap(best_K, final_grad)
            final_scale = max(abs(float(final_obj)), abs(float(obj0)), 1e-300)
            final_rel_gap = final_gap / final_scale

            info = {
                "converged": bool(final_rel_gap <= md_gap_tol_rel),
                "convergence_reason": (
                    convergence_reason
                    if final_rel_gap <= md_gap_tol_rel
                    else "max_iters"
                ),
                "iterations": int(t + 1),
                "best_iter": int(best_iter),
                "initial_objective": float(obj0),
                "objective": float(final_obj),
                "frank_wolfe_gap": float(final_gap),
                "relative_frank_wolfe_gap": float(final_rel_gap),
                "md_gap_tol_rel": float(md_gap_tol_rel),
                "best_gap_during_run": float(best_gap),
                "best_relative_gap_during_run": float(best_rel_gap),
            }

            return float(final_obj), best_K, info

        best_obj = float("inf")
        best_K = K0.copy()
        best_info = None

        for r in range(md_restarts):
            if r == 0:
                K_init = K0
            else:
                noise = rng.normal(loc=0.0, scale=md_noise_sigma, size=G)
                K_init = K0 * np.exp(noise)
                K_init = np.maximum(K_init, 1e-300)
                K_init /= float(np.sum(K_init))

            obj_r, K_r, info_r = mirror_descent(K_init)
            info_r["restart"] = int(r)

            if obj_r < best_obj:
                best_obj = float(obj_r)
                best_K = K_r
                best_info = info_r

            if info_r.get("converged", False):
                break

        tokens, members, best_K = self._safe_prune_with_priors(
            tokens,
            members,
            best_K,
            objective_weights,
            b,
            prune_tol,
        )

        G = len(members)
        if G == 0:
            return [], [], np.zeros(0, dtype=np.int64), {
                "relaxed_objective": None,
                "num_groups": 0,
                "flat_objective": False,
                "convergence": None,
            }

        obj_refine, K_refine, info_refine = mirror_descent(best_K)
        info_refine["restart"] = "refinement"

        if obj_refine < best_obj or best_info is None:
            best_obj = float(obj_refine)
            best_K = K_refine
            best_info = info_refine
        else:
            if info_refine.get("converged", False) and not best_info.get("converged", False):
                best_obj = float(obj_refine)
                best_K = K_refine
                best_info = info_refine

        final_obj, final_grad = eval_obj_and_grad(best_K)
        final_gap = self._simplex_frank_wolfe_gap(best_K, final_grad)

        initial_obj_for_scale = (
            best_info.get("initial_objective", final_obj)
            if best_info is not None
            else final_obj
        )

        final_scale = max(abs(float(final_obj)), abs(float(initial_obj_for_scale)), 1e-300)
        final_rel_gap = final_gap / final_scale

        if best_info is None:
            best_info = {}

        best_info.update(
            {
                "converged": bool(final_rel_gap <= md_gap_tol_rel),
                "convergence_reason": (
                    "frank_wolfe_gap"
                    if final_rel_gap <= md_gap_tol_rel
                    else "max_iters"
                ),
                "objective": float(final_obj),
                "frank_wolfe_gap": float(final_gap),
                "relative_frank_wolfe_gap": float(final_rel_gap),
                "md_gap_tol_rel": float(md_gap_tol_rel),
            }
        )

        raw = B * best_K

        truncation_mode = bool(getattr(self, "attempt_truncation", False))

        reps = self._round_continuous_allocation(
            raw=raw,
            B=B,
            members=members,
            objective_weights=rounding_objective_weights,
            objective_power=p,
            b=b,
            truncation_mode=truncation_mode,
            objective_mode=objective_mode,
            truncation_cost=truncation_cost,
        )

        return tokens, members, reps, {
            "relaxed_objective": float(final_obj),
            "num_groups": G,
            "flat_objective": False,
            "convergence": best_info,
        }

    # ------------------------------------------------------------------
    # Truncation scan
    # ------------------------------------------------------------------

    def _solve_overlapping_power_with_truncation(
        self,
        tokens,
        members,
        abs_coeffs,
        objective_weights_full,
        objective_power,
        objective_mode,
        b,
        B,
    ):
        """
        Attempt truncation for the overlapping informed allocation.

        Candidate active sets are generated by ranking observables by |w_j|.

        For each candidate active set S:
          - solve the relaxed allocation with inactive objective weights set to zero;
          - use the full group pool;
          - evaluate the final post-rounded energy proxy using the actually
            measured observables.
        """
        M = int(self.num_obs)
        B = int(B)

        abs_coeffs = np.asarray(abs_coeffs, dtype=np.float64).reshape(-1)
        objective_weights_full = np.asarray(objective_weights_full, dtype=np.float64).reshape(-1)
        b = np.asarray(b, dtype=np.float64).reshape(-1)

        if B <= 0 or len(members) == 0:
            self.truncation_info = {
                "attempted": True,
                "selected": False,
                "reason": "zero budget or empty group pool",
            }
            return [], [], np.zeros(0, dtype=np.int64)

        order = np.argsort(-abs_coeffs, kind="mergesort")
        positive_order = order[abs_coeffs[order] > 0.0]

        if positive_order.size == 0:
            toks, mems, reps, alloc_info = self._solve_overlapping_power_with_priors(
                tokens,
                members,
                objective_weights_full,
                objective_power,
                b,
                B,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
                rounding_objective_weights=objective_weights_full,
            )

            self.truncation_info = {
                "attempted": True,
                "selected": False,
                "reason": "all coefficients are zero",
                "allocation_info": alloc_info,
            }

            return toks, mems, reps

        candidate_sizes = self._truncation_candidate_sizes(int(positive_order.size))

        best = None
        records = []

        for candidate_id, m in enumerate(candidate_sizes):
            m = int(m)

            active = np.zeros(M, dtype=bool)
            active[positive_order[:m]] = True

            objective_weights_trial = np.zeros_like(objective_weights_full)
            objective_weights_trial[active] = objective_weights_full[active]

            toks, mems, reps, alloc_info = self._solve_overlapping_power_with_priors(
                tokens,
                members,
                objective_weights_trial,
                objective_power,
                b,
                B,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
                # During truncation, marginal rounding is allowed to optimize
                # the final post-rounded proxy rather than only the active
                # relaxed objective.
                rounding_objective_weights=objective_weights_full,
            )

            new_counts = self._counts_from_allocation(mems, reps)

            total_proxy, stat_proxy, trunc_bias, measured = (
                self._energy_proxy_from_counts(
                    abs_coeffs=abs_coeffs,
                    objective_weights=objective_weights_full,
                    objective_power=objective_power,
                    objective_mode=objective_mode,
                    b=b,
                    new_counts=new_counts,
                )
            )

            positive = abs_coeffs > 0.0
            num_truncated_positive = int(np.count_nonzero(positive & ~measured))

            convergence_info = alloc_info.get("convergence", None)

            record = {
                "candidate_id": int(candidate_id),
                "active_size": int(m),
                "num_groups_after_pruning": int(len(mems)),
                "num_groups_with_nonzero_reps": int(np.count_nonzero(reps > 0)),
                "num_measured_observables": int(np.count_nonzero(measured)),
                "num_truncated_positive_observables": int(num_truncated_positive),
                "stat_proxy": float(stat_proxy),
                "trunc_bias": float(trunc_bias),
                "total_proxy": float(total_proxy),
                "allocation_convergence": convergence_info,
            }
            records.append(record)

            if best is None or total_proxy < best["total_proxy"]:
                best = {
                    "tokens": toks,
                    "members": mems,
                    "reps": reps,
                    "active_size": int(m),
                    "total_proxy": float(total_proxy),
                    "stat_proxy": float(stat_proxy),
                    "trunc_bias": float(trunc_bias),
                    "num_measured_observables": int(np.count_nonzero(measured)),
                    "num_truncated_positive_observables": int(num_truncated_positive),
                    "allocation_info": alloc_info,
                    "candidate_id": int(candidate_id),
                }

        if best is None:
            self.truncation_info = {
                "attempted": True,
                "selected": False,
                "reason": "no candidate allocation was produced",
            }
            return [], [], np.zeros(0, dtype=np.int64)

        no_trunc_size = int(positive_order.size)
        selected_objective_truncation = best["active_size"] < no_trunc_size
        actual_truncation_after_rounding = best["num_truncated_positive_observables"] > 0

        self.truncation_info = {
            "attempted": True,

            # True if the selected candidate used fewer active observables than
            # the full positive-coefficient set.
            "selected": bool(selected_objective_truncation),

            "selected_objective_truncation": bool(selected_objective_truncation),
            "actual_truncation_after_rounding": bool(actual_truncation_after_rounding),
            "num_truncated_positive_observables": int(
                best["num_truncated_positive_observables"]
            ),

            "selected_candidate_id": int(best["candidate_id"]),
            "selected_active_size": int(best["active_size"]),
            "no_truncation_active_size": int(no_trunc_size),
            "num_candidates": int(len(candidate_sizes)),
            "num_measured_observables": int(best["num_measured_observables"]),
            "stat_proxy": float(best["stat_proxy"]),
            "trunc_bias": float(best["trunc_bias"]),
            "total_proxy": float(best["total_proxy"]),
            "selected_allocation_info": best["allocation_info"],
            "records": records,
        }

        return best["tokens"], best["members"], best["reps"]

    # ------------------------------------------------------------------
    # Public allocation entry point
    # ------------------------------------------------------------------

    def allocate_budget(self):
        """
        Offline allocation; fills settings_dict/settings_buffer and updates:

          - N_hits
          - N_hits_pairs

        Semantics:
          - prior_counts[j] = already available reusable samples for Pauli j
          - total_rounds    = new rounds to allocate now

        Modes:
          - uninformed allocation:
                uniform over groups;

          - informed non-overlap:
                exact convex solve for the power-law objective;

          - informed overlap without truncation:
                mirror descent on the relaxed overlapping power-law objective;

          - informed overlap with truncation:
                scan candidate active sets, solve the overlapping allocation
                with inactive weights set to zero, then choose the candidate
                minimizing the post-rounded energy proxy.
        """
        B = int(self.total_rounds)

        self._clear_new_scheme_state()

        self.truncation_info = {
            "attempted": False,
            "selected": False,
        }

        self.allocation_info = {
            "attempted": False,
            "mode": None,
        }

        if B <= 0 or len(self.cliques_pool) == 0:
            return

        members = self.cliques_pool
        tokens = [encode_setting_token(g) for g in members]

        G = len(members)
        if G == 0:
            return

        informed_allocation = bool(getattr(self, "informed_allocation", True))

        if not informed_allocation:
            reps = self._uniform_reps(G, B)
            self._commit_allocation(tokens, members, reps)

            self.allocation_info = {
                "attempted": True,
                "mode": "uniform",
                "num_groups": int(G),
            }
            return

        abs_coeffs, objective_weights, objective_power, objective_mode = (
            self._energy_objective_params()
        )

        if hasattr(self, "prior_counts"):
            b = np.asarray(self.prior_counts, dtype=np.float64).reshape(-1)
        else:
            b = np.zeros(int(self.num_obs), dtype=np.float64)

        if b.shape != (self.num_obs,):
            raise ValueError(
                f"prior_counts must have shape ({self.num_obs},), got {b.shape}."
            )

        if np.any(b < 0.0):
            raise ValueError("prior_counts must be nonnegative.")

        is_overlapping = bool(getattr(self, "is_overlapping", False))

        if not is_overlapping:
            raw = self._solve_nonoverlap_power_with_priors(
                members=members,
                objective_weights=objective_weights,
                objective_power=objective_power,
                b=b,
                B=B,
            )

            reps = self._round_raw_allocation_largest_fraction(raw, B)

            self._commit_allocation(tokens, members, reps)

            self.allocation_info = {
                "attempted": True,
                "mode": "informed_nonoverlap",
                "allocation_objective": objective_mode,
                "objective_power": float(objective_power),
                "num_groups": int(G),
            }
            return

        if bool(getattr(self, "attempt_truncation", False)):
            tokens, members, reps = self._solve_overlapping_power_with_truncation(
                tokens=tokens,
                members=members,
                abs_coeffs=abs_coeffs,
                objective_weights_full=objective_weights,
                objective_power=objective_power,
                objective_mode=objective_mode,
                b=b,
                B=B,
            )

            self.allocation_info = {
                "attempted": True,
                "mode": "informed_overlap_with_truncation",
                "allocation_objective": objective_mode,
                "objective_power": float(objective_power),
                "truncation_info": self.truncation_info,
            }

        else:
            tokens, members, reps, alloc_info = self._solve_overlapping_power_with_priors(
                tokens_in=tokens,
                members_in=members,
                objective_weights=objective_weights,
                objective_power=objective_power,
                b=b,
                B=B,
                objective_mode=objective_mode,
                truncation_cost=abs_coeffs,
                rounding_objective_weights=objective_weights,
            )

            self.allocation_info = {
                "attempted": True,
                "mode": "informed_overlap",
                "allocation_objective": objective_mode,
                "objective_power": float(objective_power),
                **alloc_info,
            }

        self._commit_allocation(tokens, members, reps)